# Basics Refresher

In [10]:
import pandas as pd
import numpy as np

In [11]:
players = ['Lebron', 'JT', 'KD']

In [12]:
type(players)

list

In [16]:
for player in players:
    if player == 'Lebron':
        continue
    print(player)

JT
KD

In [18]:
lebron_dict = {
    'name': 'Lebron',
    'team': 'Lakers',
    'ppg': 25.6
}

In [20]:
for key in lebron_dict:
    print(lebron_dict[key])

Lebron
Lakers
25.6

In [21]:
def points_per_game(points, games_played):
    ppg = points / games_played
    return ppg

In [24]:
points = 1500
games_played = 81
harden_ppg = (points_per_game(points, games_played))
print(round(harden_ppg, 1))

18.5

In [25]:
jokic_20_stats = np.array([594, 132, 123])
jokic_21_stats = np.array([765, 222, 213])
jokic_22_stats = np.array([923, 312, 345])

In [26]:
jokic_career_stats = jokic_20_stats + jokic_21_stats + jokic_22_stats

In [28]:
total_gp = 300

In [32]:
jokic_career_stats / total_gp

array([7.60666667, 2.22      , 2.27      ])

# pandas
# creating a dataframe

In [44]:
celtics_dict = {'first_name': ['Kristaps', 'Al', 'Derrick', 'Jayson', 'Jaylen'], 
        'last_name': ['Porzingis', 'Horford', 'White', 'Tatum', 'Brown'], 
        'ppg': [27.4, 18.7, 9.9, 18.3, 7.8], 
        'apg': [8.3, 2.5, 5.4, 3.0, 1.4],
        'rpg': [8.5, 5.5, 5.3, 5.1, 3.7]}

In [45]:
df = pd.DataFrame(celtics_dict)

In [46]:
print(df)

  first_name  last_name   ppg  apg  rpg
0   Kristaps  Porzingis  27.4  8.3  8.5
1         Al    Horford  18.7  2.5  5.5
2    Derrick      White   9.9  5.4  5.3
3     Jayson      Tatum  18.3  3.0  5.1
4     Jaylen      Brown   7.8  1.4  3.7

In [47]:
df = pd.DataFrame(celtics_dict, index=[1,2,3,4,5])

In [48]:
print(df)

  first_name  last_name   ppg  apg  rpg
1   Kristaps  Porzingis  27.4  8.3  8.5
2         Al    Horford  18.7  2.5  5.5
3    Derrick      White   9.9  5.4  5.3
4     Jayson      Tatum  18.3  3.0  5.1
5     Jaylen      Brown   7.8  1.4  3.7

In [49]:
df = pd.DataFrame(celtics_dict, index=['C','PF','PG','SF','SG'])

In [50]:
print(df)

   first_name  last_name   ppg  apg  rpg
C    Kristaps  Porzingis  27.4  8.3  8.5
PF         Al    Horford  18.7  2.5  5.5
PG    Derrick      White   9.9  5.4  5.3
SF     Jayson      Tatum  18.3  3.0  5.1
SG     Jaylen      Brown   7.8  1.4  3.7

In [51]:
stats = [['Tatum', 8, 5], ['Brown', 1, 2], ['White', 2, 3]]

In [52]:
df = pd.DataFrame(stats, columns=['player', 'OREB', 'DREB'])

In [53]:
print(df)

  player  OREB  DREB
0  Tatum     8     5
1  Brown     1     2
2  White     2     3

In [54]:
# create a series

In [55]:
rebs = [8, 5, 6, 12, 3]

In [63]:
df = pd.DataFrame(rebs, columns=['Tatum_reb'], index=[1,2,3,4,5])

In [64]:
print(df)

   Tatum_reb
1          8
2          5
3          6
4         12
5          3

In [ ]:
# reading csv files

In [67]:
df = pd.read_csv('../stats-csv/player_info.csv')

In [68]:
df.head(10)

   player_id            player_name season_id
0        920             A.C. Green   1996-97
1        243            Aaron McKie   1996-97
2       1425         Aaron Williams   1996-97
3        768              Acie Earl   1996-97
4        228             Adam Keefe   1996-97
5        154        Adrian Caldwell   1996-97
6        673         Alan Henderson   1996-97
7       1059  Aleksandar Djordjevic   1996-97
8        275          Allan Houston   1996-97
9        947          Allen Iverson   1996-97

In [70]:
# make player_id the index
df = pd.read_csv('../stats-csv/player_info.csv', index_col='player_id')

In [72]:
df.head(10)

                     player_name season_id
player_id
920                   A.C. Green   1996-97
243                  Aaron McKie   1996-97
1425              Aaron Williams   1996-97
768                    Acie Earl   1996-97
228                   Adam Keefe   1996-97
154              Adrian Caldwell   1996-97
673               Alan Henderson   1996-97
1059       Aleksandar Djordjevic   1996-97
275                Allan Houston   1996-97
947                Allen Iverson   1996-97

In [75]:
# only load certain columns
df = pd.read_csv('../stats-csv/player_info.csv', usecols=['player_id','season_id'])

In [76]:
df.head(5)

   player_id season_id
0        920   1996-97
1        243   1996-97
2       1425   1996-97
3        768   1996-97
4        228   1996-97

In [77]:
# attributes and methods
df = pd.read_csv('../stats-csv/player_general_traditional_per_game_data.csv')

In [79]:
df.shape
# rows, cols

(10633, 21)

In [80]:
df.dtypes

player_id      int64
season_id     object
gp           float64
age          float64
min          float64
fgm          float64
fga          float64
fg_pct       float64
fg3m         float64
fg3a         float64
fg3_pct      float64
ftm          float64
fta          float64
ft_pct       float64
oreb         float64
dreb         float64
ast          float64
tov          float64
stl          float64
blk          float64
pts          float64
dtype: object

In [81]:
df.head(10)

,player_id,season_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,...,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
0,471,1996-97,41.0,NaN,13.3,1.1,3.3,0.331,0.2,0.7,...,1.0,1.2,0.875,0.7,1.8,1.4,0.8,0.2,0.3,3.4
1,920,1996-97,83.0,33.0,30.8,2.8,5.8,0.483,0.0,0.2,...,1.5,2.4,0.650,2.7,5.2,0.8,0.9,0.8,0.2,7.2
2,243,1996-97,83.0,24.0,20.4,1.8,4.4,0.411,0.5,1.2,...,1.1,1.3,0.836,0.5,2.2,1.9,1.1,0.9,0.3,5.2
3,1425,1996-97,33.0,25.0,17.8,2.6,4.5,0.574,0.0,0.0,...,1.0,1.5,0.673,1.9,2.5,0.5,1.0,0.5,0.9,6.2
4,768,1996-97,47.0,27.0,11.1,1.4,3.8,0.374,0.0,0.1,...,1.1,1.8,0.643,0.7,1.3,0.4,0.7,0.3,0.6,4.0
5,228,1996-97,62.0,27.0,15.4,1.3,2.6,0.513,0.0,0.0,...,1.1,1.7,0.689,1.2,2.3,0.5,0.7,0.5,0.2,3.8
6,154,1996-97,45.0,30.0,13.1,0.9,2.0,0.435,0.0,0.0,...,0.5,1.1,0.420,1.3,2.4,0.3,0.6,0.4,0.2,2.2
7,673,1996-97,30.0,24.0,17.2,2.6,5.4,0.475,0.0,0.0,...,1.5,2.5,0.600,1.6,2.3,0.8,1.0,0.7,0.2,6.6
8,1059,1996-97,8.0,29.0,7.9,1.0,2.0,0.500,0.6,0.9,...,0.5,0.6,0.800,0.1,0.5,0.6,0.6,0.0,0.0,3.1
9,275,1996-97,81.0,26.0,34.3,5.4,12.7,0.423,1.8,4.7,...,2.2,2.7,0.803,0.5,2.4,2.2,2.1,0.5,0.2,14.8

In [82]:
df.tail(10)

,player_id,season_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,...,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
10623,201163,2018-19,51.0,31.0,23.1,2.2,5.4,0.418,1.2,3.1,...,0.4,0.5,0.720,0.9,3.3,1.6,0.9,0.5,0.4,6.0
10624,1628999,2018-19,2.0,22.0,6.5,0.5,2.0,0.250,0.0,0.5,...,0.0,0.0,0.000,0.5,1.0,0.0,0.0,0.5,0.0,1.0
10625,1627812,2018-19,71.0,25.0,15.0,2.2,5.0,0.435,0.8,2.1,...,0.8,0.9,0.896,0.2,1.4,1.9,0.6,0.5,0.1,5.9
10626,1629139,2018-19,15.0,24.0,11.6,1.0,3.4,0.294,0.1,1.1,...,0.5,0.7,0.700,0.3,1.8,0.5,0.4,0.3,0.1,2.6
10627,1628380,2018-19,77.0,21.0,17.6,2.5,5.2,0.473,0.5,1.6,...,1.2,1.6,0.746,1.4,2.8,0.9,1.0,0.3,0.9,6.6
10628,203897,2018-19,63.0,24.0,34.5,8.4,18.0,0.467,1.9,5.1,...,5.0,6.0,0.832,0.6,4.0,4.5,3.4,1.0,0.4,23.7
10629,1629155,2018-19,1.0,26.0,3.8,0.0,1.0,0.000,0.0,1.0,...,0.0,0.0,0.000,0.0,0.0,0.0,1.0,1.0,0.0,0.0
10630,2585,2018-19,68.0,35.0,12.9,1.3,2.8,0.440,0.0,0.1,...,1.4,1.8,0.782,1.5,2.4,1.3,0.8,0.5,0.3,3.9
10631,1629015,2018-19,6.0,19.0,18.4,2.3,5.7,0.412,1.0,2.7,...,1.0,1.3,0.750,0.5,1.7,1.7,1.0,0.3,0.3,6.7
10632,1627753,2018-19,1.0,23.0,1.0,1.0,1.0,1.000,0.0,0.0,...,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,2.0

In [83]:
# random sample of data
df.sample(20)

,player_id,season_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,...,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
8328,201952,2014-15,73.0,27.0,30.5,5.6,12.2,0.460,1.0,2.8,...,3.8,4.4,0.862,0.4,2.1,7.0,2.8,1.7,0.4,15.9
5522,2749,2008-09,42.0,27.0,31.2,6.4,12.6,0.503,2.0,4.3,...,2.0,2.3,0.887,0.5,3.0,5.4,2.0,1.2,0.1,16.7
3773,1919,2004-05,42.0,27.0,10.0,1.3,3.0,0.438,0.2,0.7,...,0.4,0.6,0.640,0.6,1.2,0.9,0.6,0.4,0.1,3.2
2115,1763,2000-01,57.0,25.0,12.2,1.4,2.5,0.556,0.1,0.2,...,0.5,0.8,0.614,1.1,0.9,0.5,0.4,0.6,0.2,3.4
6974,201178,2011-12,3.0,25.0,5.7,0.7,1.7,0.400,0.0,0.0,...,1.3,2.0,0.667,0.7,2.3,0.3,0.0,0.7,0.0,2.7
2410,1983,2001-02,24.0,26.0,11.6,0.8,1.8,0.476,0.0,0.1,...,0.7,1.0,0.667,0.1,1.0,2.4,0.6,0.4,0.0,2.4
573,96,1997-98,78.0,35.0,35.2,5.6,11.5,0.485,0.8,1.9,...,3.8,4.5,0.844,1.7,5.4,4.4,2.2,0.8,0.2,15.7
9108,203462,2016-17,15.0,22.0,14.3,2.4,4.4,0.545,0.3,1.0,...,2.2,2.8,0.786,0.5,1.4,1.6,0.9,0.3,0.3,7.3
2434,252,2001-02,80.0,38.0,38.0,7.9,17.5,0.454,0.1,0.3,...,6.4,8.0,0.797,1.8,6.8,4.3,3.3,1.9,0.7,22.4
6567,202335,2010-11,52.0,22.0,16.7,2.9,5.1,0.558,0.0,0.0,...,0.6,0.8,0.714,1.7,2.2,0.8,0.6,0.3,0.7,6.3
5207,2229,2007-08,54.0,33.0,13.3,1.9,5.4,0.348,0.6,1.8,...,0.7,0.9,0.813,0.3,1.0,1.1,0.7,0.4,0.0,5.0
10127,1629116,2018-19,2.0,24.0,7.4,0.5,2.5,0.200,0.0,0.0,...,0.5,1.0,0.500,1.0,1.0,0.0,0.0,0.5,0.0,1.5
9280,203950,2016-17,2.0,23.0,3.3,0.5,0.5,1.000,0.0,0.0,...,0.5,1.0,0.500,0.5,0.5,1.0,0.0,0.5,0.0,1.5
10049,202699,2017-18,80.0,25.0,33.3,7.0,15.3,0.460,2.3,5.6,...,2.2,2.7,0.829,0.7,4.7,2.4,1.3,0.9,0.4,18.6
6755,101108,2011-12,60.0,27.0,36.3,7.1,14.8,0.478,1.3,3.6,...,4.3,5.0,0.861,0.7,2.9,9.1,2.1,2.5,0.1,19.8
9939,203118,2017-18,76.0,29.0,18.5,3.6,6.9,0.527,0.9,2.1,...,0.7,1.0,0.658,0.7,2.6,1.1,1.0,0.3,0.1,8.8
2059,2130,2000-01,53.0,26.0,16.0,1.7,4.2,0.414,1.0,2.6,...,0.5,0.6,0.903,0.2,1.0,1.3,0.6,0.4,0.0,5.0
2726,1894,2002-03,64.0,23.0,31.3,5.4,12.1,0.444,1.0,2.8,...,5.1,6.3,0.802,1.2,3.8,1.9,2.3,0.9,0.3,16.8
9239,201609,2016-17,73.0,31.0,33.7,7.3,15.4,0.475,1.6,4.0,...,4.1,5.2,0.790,0.8,3.0,5.8,2.9,1.2,0.2,20.3
2997,937,2002-03,64.0,37.0,29.9,4.1,9.3,0.444,0.6,2.1,...,1.9,2.3,0.818,0.9,3.5,4.5,2.6,1.6,0.4,10.8

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10633 entries, 0 to 10632
Data columns (total 21 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   player_id  10633 non-null  int64
 1   season_id  10633 non-null  object
 2   gp         10633 non-null  float64
 3   age        10631 non-null  float64
 4   min        10633 non-null  float64
 5   fgm        10633 non-null  float64
 6   fga        10633 non-null  float64
 7   fg_pct     10633 non-null  float64
 8   fg3m       10633 non-null  float64
 9   fg3a       10633 non-null  float64
 10  fg3_pct    10633 non-null  float64
 11  ftm        10633 non-null  float64
 12  fta        10633 non-null  float64
 13  ft_pct     10633 non-null  float64
 14  oreb       10633 non-null  float64
 15  dreb       10633 non-null  float64
 16  ast        10633 non-null  float64
 17  tov        10633 non-null  float64
 18  stl        10633 non-null  float64
 19  blk        10633 non-null  float64
 20  pts        10633 non-null  float64
dtypes: float64(19), int64(1), object(1)
memory usage: 1.7+ MB

In [85]:
df.describe()

,player_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
count,1.063300e+04,10633.000000,10631.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000,10633.000000
mean,1.684222e+05,52.633782,27.235255,20.398853,3.031468,6.798354,0.433469,0.545359,1.562682,0.235817,1.495429,2.003480,0.698231,0.970159,2.589119,1.796398,1.186043,0.646929,0.412602,8.101129
std,3.882780e+05,25.115265,4.344703,10.099563,2.159450,4.594357,0.097001,0.661287,1.743706,0.179157,1.397361,1.769024,0.195102,0.831041,1.789594,1.789208,0.791090,0.449050,0.481362,5.903179
min,2.000000e+00,1.000000,18.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.495000e+03,33.000000,24.000000,12.100000,1.300000,3.200000,0.398000,0.000000,0.100000,0.000000,0.500000,0.800000,0.643000,0.400000,1.300000,0.600000,0.600000,0.300000,0.100000,3.500000
50%,2.501000e+03,59.000000,27.000000,19.800000,2.500000,5.700000,0.437000,0.300000,1.000000,0.298000,1.100000,1.500000,0.745000,0.700000,2.200000,1.200000,1.000000,0.600000,0.300000,6.600000
75%,2.018800e+05,75.000000,30.000000,28.700000,4.300000,9.500000,0.479000,0.900000,2.600000,0.364000,2.000000,2.700000,0.814000,1.400000,3.400000,2.400000,1.600000,0.900000,0.500000,11.500000
max,1.629541e+06,85.000000,44.000000,44.400000,12.200000,27.800000,1.000000,5.100000,13.200000,1.000000,9.700000,13.100000,1.000000,6.800000,11.500000,11.700000,5.700000,2.900000,3.900000,36.100000

In [86]:
df.sum()

player_id                                           1790833752
season_id    1996-971996-971996-971996-971996-971996-971996...
gp                                                      559655
age                                                     289538
min                                                     216901
fgm                                                    32233.6
fga                                                    72286.9
fg_pct                                                 4609.07
fg3m                                                    5798.8
fg3a                                                     16616
fg3_pct                                                2507.45
ftm                                                    15900.9
fta                                                      21303
ft_pct                                                 7424.29
oreb                                                   10315.7
dreb                                                   27530.1
ast                                                    19101.1
tov                                                    12611.2
stl                                                     6878.8
blk                                                     4387.2
pts                                                    86139.3
dtype: object

In [87]:
df.mean()

player_id    168422.246967
gp               52.633782
age              27.235255
min              20.398853
fgm               3.031468
fga               6.798354
fg_pct            0.433469
fg3m              0.545359
fg3a              1.562682
fg3_pct           0.235817
ftm               1.495429
fta               2.003480
ft_pct            0.698231
oreb              0.970159
dreb              2.589119
ast               1.796398
tov               1.186043
stl               0.646929
blk               0.412602
pts               8.101129
dtype: float64

In [88]:
df.corr()

,player_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
player_id,1.000000,-0.117966,-0.327878,-0.138399,-0.088626,-0.091591,-0.013139,0.031839,0.047200,0.053466,-0.117921,-0.121414,-0.070711,-0.104069,-0.076786,-0.073226,-0.128919,-0.094299,-0.058878,-0.089121
gp,-0.117966,1.000000,0.031932,0.661571,0.558798,0.537544,0.323238,0.338970,0.326380,0.252203,0.436210,0.432054,0.401575,0.350474,0.499179,0.391819,0.473280,0.482834,0.293747,0.550499
age,-0.327878,0.031932,1.000000,0.068160,-0.010243,-0.005897,-0.011013,0.060671,0.048133,0.017836,-0.026634,-0.045631,0.080744,-0.034389,0.048336,0.079816,-0.013969,0.023266,-0.036354,-0.006939
min,-0.138399,0.661571,0.068160,1.000000,0.898696,0.902499,0.265402,0.512537,0.521027,0.286004,0.763601,0.759884,0.391170,0.468688,0.741098,0.672098,0.821540,0.766862,0.381113,0.896016
fgm,-0.088626,0.558798,-0.010243,0.898696,1.000000,0.981887,0.306843,0.494028,0.500119,0.269023,0.856325,0.848208,0.355666,0.440062,0.712868,0.627075,0.835310,0.681252,0.370746,0.989830
fga,-0.091591,0.537544,-0.005897,0.902499,0.981887,1.000000,0.188154,0.569256,0.588161,0.317116,0.846021,0.825272,0.378002,0.353804,0.653903,0.665869,0.844743,0.707331,0.291224,0.982662
fg_pct,-0.013139,0.323238,-0.011013,0.265402,0.306843,0.188154,1.000000,-0.050848,-0.097441,-0.027911,0.222654,0.258393,0.158601,0.401689,0.362039,0.052194,0.188453,0.131418,0.346540,0.271633
fg3m,0.031839,0.338970,0.060671,0.512537,0.494028,0.569256,-0.050848,1.000000,0.984159,0.589520,0.341470,0.268837,0.352018,-0.234495,0.132096,0.480875,0.386329,0.456960,-0.156865,0.554222
fg3a,0.047200,0.326380,0.048133,0.521027,0.500119,0.588161,-0.097441,0.984159,1.000000,0.567381,0.356412,0.284632,0.352993,-0.244986,0.131054,0.507521,0.410626,0.482190,-0.167452,0.560556
fg3_pct,0.053466,0.252203,0.017836,0.286004,0.269023,0.317116,-0.027911,0.589520,0.567381,1.000000,0.160462,0.099531,0.329966,-0.274225,-0.007294,0.334241,0.210239,0.295806,-0.212880,0.300943
ftm,-0.117921,0.436210,-0.026634,0.763601,0.856325,0.846021,0.222654,0.341470,0.356412,0.160462,1.000000,0.980969,0.356486,0.406706,0.626931,0.569923,0.804884,0.599211,0.335838,0.901634
fta,-0.121414,0.432054,-0.045631,0.759884,0.848208,0.825272,0.258393,0.268837,0.284632,0.099531,0.980969,1.000000,0.277477,0.491190,0.676289,0.532583,0.804858,0.587889,0.411419,0.883174
ft_pct,-0.070711,0.401575,0.080744,0.391170,0.355666,0.378002,0.158601,0.352018,0.352993,0.329966,0.356486,0.277477,1.000000,0.001588,0.181000,0.315181,0.304059,0.299414,-0.009240,0.384167
oreb,-0.104069,0.350474,-0.034389,0.468688,0.440062,0.353804,0.401689,-0.234495,-0.244986,-0.274225,0.406706,0.491190,0.001588,1.000000,0.779032,-0.011059,0.349736,0.222488,0.683148,0.392206
dreb,-0.076786,0.499179,0.048336,0.741098,0.712868,0.653903,0.362039,0.132096,0.131054,-0.007294,0.626931,0.676289,0.181000,0.779032,1.000000,0.306302,0.609042,0.472102,0.663878,0.685015
ast,-0.073226,0.391819,0.079816,0.672098,0.627075,0.665869,0.052194,0.480875,0.507521,0.334241,0.569923,0.532583,0.315181,-0.011059,0.306302,1.000000,0.778715,0.709135,-0.020056,0.647640
tov,-0.128919,0.473280,-0.013969,0.821540,0.835310,0.844743,0.188453,0.386329,0.410626,0.210239,0.804884,0.804858,0.304059,0.349736,0.609042,0.778715,1.000000,0.710621,0.291595,0.845105
stl,-0.094299,0.482834,0.023266,0.766862,0.681252,0.707331,0.131418,0.456960,0.482190,0.295806,0.599211,0.587889,0.299414,0.222488,0.472102,0.709135,0.710621,1.000000,0.164976,0.691502
blk,-0.058878,0.293747,-0.036354,0.381113,0.370746,0.291224,0.346540,-0.156865,-0.167452,-0.212880,0.335838,0.411419,-0.009240,0.683148,0.663878,-0.020056,0.291595,0.164976,1.000000,0.333186
pts,-0.089121,0.550499,-0.006939,0.896016,0.989830,0.982662,0.271633,0.554222,0.560556,0.300943,0.901634,0.883174,0.384167,0.392206,0.685015,0.647640,0.845105,0.691502,0.333186,1.000000

In [89]:
df.count()

player_id    10633
season_id    10633
gp           10633
age          10631
min          10633
fgm          10633
fga          10633
fg_pct       10633
fg3m         10633
fg3a         10633
fg3_pct      10633
ftm          10633
fta          10633
ft_pct       10633
oreb         10633
dreb         10633
ast          10633
tov          10633
stl          10633
blk          10633
pts          10633
dtype: int64

In [90]:
df.max()

player_id    1629541
season_id    2018-19
gp                85
age               44
min             44.4
fgm             12.2
fga             27.8
fg_pct             1
fg3m             5.1
fg3a            13.2
fg3_pct            1
ftm              9.7
fta             13.1
ft_pct             1
oreb             6.8
dreb            11.5
ast             11.7
tov              5.7
stl              2.9
blk              3.9
pts             36.1
dtype: object

In [91]:
df.min()

player_id          2
season_id    1996-97
gp                 1
age               18
min              0.1
fgm                0
fga                0
fg_pct             0
fg3m               0
fg3a               0
fg3_pct            0
ftm                0
fta                0
ft_pct             0
oreb               0
dreb               0
ast                0
tov                0
stl                0
blk                0
pts                0
dtype: object

In [92]:
df.median()

player_id    2501.000
gp             59.000
age            27.000
min            19.800
fgm             2.500
fga             5.700
fg_pct          0.437
fg3m            0.300
fg3a            1.000
fg3_pct         0.298
ftm             1.100
fta             1.500
ft_pct          0.745
oreb            0.700
dreb            2.200
ast             1.200
tov             1.000
stl             0.600
blk             0.300
pts             6.600
dtype: float64

In [93]:
df.std()

player_id    388278.044987
gp               25.115265
age               4.344703
min              10.099563
fgm               2.159450
fga               4.594357
fg_pct            0.097001
fg3m              0.661287
fg3a              1.743706
fg3_pct           0.179157
ftm               1.397361
fta               1.769024
ft_pct            0.195102
oreb              0.831041
dreb              1.789594
ast               1.789208
tov               0.791090
stl               0.449050
blk               0.481362
pts               5.903179
dtype: float64

In [94]:
# dataframe columns

In [103]:
df = pd.read_csv('../stats-csv/player_stats_total.csv')

In [150]:
df_small = df.sample(20)

In [108]:
# list the column names
list(df_small)

['player_name',
 'player_id',
 'season_id',
 'gp',
 'age',
 'min',
 'fgm',
 'fga',
 'fg3m',
 'ftm',
 'fta',
 'oreb',
 'dreb',
 'ast',
 'tov',
 'stl',
 'blk',
 'pts']

In [109]:
# select 1 column using dot notation
df_small.player_name

2577          Jerian Grant
100         Jamal Crawford
278                   Nene
377            Kyle Korver
1039          Corey Brewer
74             Jason Terry
2688      Isaiah Whitehead
1697         Blake Griffin
901      LaMarcus Aldridge
2661           Buddy Hield
2359            Seth Curry
2434    Glenn Robinson III
413            Matt Barnes
530               JR Smith
2589       Josh Richardson
1155           Mike Conley
1198         Spencer Hawes
2052      Tristan Thompson
1087           Joakim Noah
1982         Klay Thompson
Name: player_name, dtype: object

In [110]:
# or pass the column name
df_small['pts']

2577     426.0
100     1280.0
278      754.0
377      739.0
1039     998.0
74       307.0
2688     543.0
1697    1440.0
901     1769.0
2661     866.0
2359     898.0
2434     171.0
413      716.0
530      907.0
2589     341.0
1155    1168.0
1198     340.0
2052     494.0
1087     485.0
1982    1488.0
Name: pts, dtype: float64

In [111]:
type(df_small['pts'])

pandas.core.series.Series

In [112]:
df_small[['player_name', 'pts']]

             player_name     pts
2577        Jerian Grant   426.0
100       Jamal Crawford  1280.0
278                 Nene   754.0
377          Kyle Korver   739.0
1039        Corey Brewer   998.0
74           Jason Terry   307.0
2688    Isaiah Whitehead   543.0
1697       Blake Griffin  1440.0
901    LaMarcus Aldridge  1769.0
2661         Buddy Hield   866.0
2359          Seth Curry   898.0
2434  Glenn Robinson III   171.0
413          Matt Barnes   716.0
530             JR Smith   907.0
2589     Josh Richardson   341.0
1155         Mike Conley  1168.0
1198       Spencer Hawes   340.0
2052    Tristan Thompson   494.0
1087         Joakim Noah   485.0
1982       Klay Thompson  1488.0

In [113]:
# specify a list of columns to reduce clutter
list_of_cols = ['player_name', 'ftm', 'fta']

In [114]:
df_small[list_of_cols]

             player_name    ftm    fta
2577        Jerian Grant   96.0  123.0
100       Jamal Crawford  300.0  344.0
278                 Nene  155.0  266.0
377          Kyle Korver   45.0   54.0
1039        Corey Brewer  163.0  227.0
74           Jason Terry   24.0   29.0
2688    Isaiah Whitehead   91.0  113.0
1697       Blake Griffin  281.0  426.0
901    LaMarcus Aldridge  351.0  444.0
2661         Buddy Hield   64.0   76.0
2359          Seth Curry   85.0  100.0
2434  Glenn Robinson III   27.0   39.0
413          Matt Barnes  108.0  146.0
530             JR Smith  128.0  178.0
2589     Josh Richardson   42.0   63.0
1155         Mike Conley  234.0  282.0
1198       Spencer Hawes   54.0   65.0
2052    Tristan Thompson  106.0  192.0
1087         Joakim Noah  105.0  174.0
1982       Klay Thompson  147.0  185.0

In [172]:
# iloc to specify the columns with column indexes
# iloc function can be used to select a specific row or column from the data set
df_small.iloc[:,0]

493             Beno Udrih
1338          Goran Dragic
64             Jason Terry
970            Steve Novak
238          Manu Ginobili
2103    Donatas Motiejunas
509           Devin Harris
2606       Larry Nance Jr.
801        Marvin Williams
1819         Larry Sanders
1453         Ryan Anderson
1741           Evan Turner
2739     Willy Hernangomez
1821         Larry Sanders
2684         Georges Niang
2659         Brice Johnson
1505         DeMar DeRozan
269                   Nene
1198         Spencer Hawes
1954             Jon Leuer
Name: player_name, dtype: object

In [117]:
df_small.iloc[:,0:3]

             player_name  player_id season_id
2577        Jerian Grant    1626170   2015-16
100       Jamal Crawford       2037   2008-09
278                 Nene       2403   2013-14
377          Kyle Korver       2594   2015-16
1039        Corey Brewer     201147   2013-14
74           Jason Terry       1891   2016-17
2688    Isaiah Whitehead    1627785   2016-17
1697       Blake Griffin     201933   2012-13
901    LaMarcus Aldridge     200746   2010-11
2661         Buddy Hield    1627741   2016-17
2359          Seth Curry     203552   2016-17
2434  Glenn Robinson III     203922   2015-16
413          Matt Barnes       2440   2009-10
530             JR Smith       2747   2007-08
2589     Josh Richardson    1626196   2015-16
1155         Mike Conley     201144   2012-13
1198       Spencer Hawes     201150   2015-16
2052    Tristan Thompson     202684   2011-12
1087         Joakim Noah     201149   2014-15
1982       Klay Thompson     202691   2013-14

In [119]:
df_small.iloc[:, [0,1,2,6,7]]

             player_name  player_id season_id    fgm     fga
2577        Jerian Grant    1626170   2015-16  154.0   391.0
100       Jamal Crawford       2037   2008-09  419.0  1022.0
278                 Nene       2403   2013-14  299.0   594.0
377          Kyle Korver       2594   2015-16  268.0   617.0
1039        Corey Brewer     201147   2013-14  388.0   807.0
74           Jason Terry       1891   2016-17  105.0   243.0
2688    Isaiah Whitehead    1627785   2016-17  204.0   508.0
1697       Blake Griffin     201933   2012-13  577.0  1072.0
901    LaMarcus Aldridge     200746   2010-11  707.0  1415.0
2661         Buddy Hield    1627741   2016-17  327.0   767.0
2359          Seth Curry     203552   2016-17  338.0   703.0
2434  Glenn Robinson III     203922   2015-16   65.0   151.0
413          Matt Barnes       2440   2009-10  271.0   557.0
530             JR Smith       2747   2007-08  311.0   674.0
2589     Josh Richardson    1626196   2015-16  123.0   272.0
1155         Mike Conley     201144   2012-13  414.0   940.0
1198       Spencer Hawes     201150   2015-16  124.0   306.0
2052    Tristan Thompson     202684   2011-12  194.0   442.0
1087         Joakim Noah     201149   2014-15  190.0   427.0
1982       Klay Thompson     202691   2013-14  559.0  1259.0

In [120]:
# adding and deleting columns

In [121]:
df_small

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
2577,Jerian Grant,1626170,2015-16,76.0,23.0,1264.890,154.0,391.0,22.0,96.0,123.0,23.0,120.0,177.0,87.0,50.0,10.0,426.0
100,Jamal Crawford,2037,2008-09,65.0,29.0,2478.300,419.0,1022.0,142.0,300.0,344.0,23.0,170.0,288.0,148.0,57.0,13.0,1280.0
278,Nene,2403,2013-14,53.0,31.0,1560.320,299.0,594.0,1.0,155.0,266.0,65.0,229.0,153.0,117.0,64.0,47.0,754.0
377,Kyle Korver,2594,2015-16,80.0,35.0,2400.810,268.0,617.0,158.0,45.0,54.0,14.0,246.0,164.0,98.0,60.0,35.0,739.0
1039,Corey Brewer,201147,2013-14,81.0,28.0,2609.350,388.0,807.0,59.0,163.0,227.0,63.0,144.0,135.0,105.0,151.0,30.0,998.0
74,Jason Terry,1891,2016-17,74.0,39.0,1364.900,105.0,243.0,73.0,24.0,29.0,15.0,91.0,98.0,36.0,46.0,20.0,307.0
2688,Isaiah Whitehead,1627785,2016-17,73.0,22.0,1643.470,204.0,508.0,44.0,91.0,113.0,32.0,152.0,192.0,142.0,42.0,36.0,543.0
1697,Blake Griffin,201933,2012-13,80.0,24.0,2598.410,577.0,1072.0,5.0,281.0,426.0,186.0,476.0,299.0,185.0,97.0,50.0,1440.0
901,LaMarcus Aldridge,200746,2010-11,81.0,25.0,3211.550,707.0,1415.0,4.0,351.0,444.0,278.0,431.0,170.0,153.0,82.0,94.0,1769.0
2661,Buddy Hield,1627741,2016-17,82.0,23.0,1888.210,327.0,767.0,148.0,64.0,76.0,35.0,234.0,121.0,101.0,38.0,9.0,866.0
2359,Seth Curry,203552,2016-17,70.0,26.0,2028.850,338.0,703.0,137.0,85.0,100.0,25.0,154.0,189.0,92.0,79.0,7.0,898.0
2434,Glenn Robinson III,203922,2015-16,45.0,22.0,508.182,65.0,151.0,14.0,27.0,39.0,12.0,56.0,26.0,18.0,17.0,9.0,171.0
413,Matt Barnes,2440,2009-10,81.0,30.0,2097.030,271.0,557.0,66.0,108.0,146.0,106.0,339.0,134.0,112.0,59.0,30.0,716.0
530,JR Smith,2747,2007-08,74.0,22.0,1420.720,311.0,674.0,157.0,128.0,178.0,43.0,109.0,128.0,112.0,62.0,12.0,907.0
2589,Josh Richardson,1626196,2015-16,52.0,22.0,1106.970,123.0,272.0,53.0,42.0,63.0,21.0,86.0,73.0,35.0,36.0,25.0,341.0
1155,Mike Conley,201144,2012-13,80.0,25.0,2756.540,414.0,940.0,106.0,234.0,282.0,43.0,182.0,487.0,189.0,174.0,24.0,1168.0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.900,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0
2052,Tristan Thompson,202684,2011-12,60.0,21.0,1423.700,194.0,442.0,0.0,106.0,192.0,187.0,202.0,27.0,81.0,27.0,62.0,494.0
1087,Joakim Noah,201149,2014-15,67.0,30.0,2048.650,190.0,427.0,0.0,105.0,174.0,219.0,427.0,312.0,123.0,48.0,74.0,485.0
1982,Klay Thompson,202691,2013-14,81.0,24.0,2867.820,559.0,1259.0,223.0,147.0,185.0,38.0,211.0,181.0,135.0,74.0,37.0,1488.0

In [123]:
# adding a column for points per game
df_small['ppg'] = 0

In [124]:
df_small

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts,ppg
2577,Jerian Grant,1626170,2015-16,76.0,23.0,1264.890,154.0,391.0,22.0,96.0,123.0,23.0,120.0,177.0,87.0,50.0,10.0,426.0,0
100,Jamal Crawford,2037,2008-09,65.0,29.0,2478.300,419.0,1022.0,142.0,300.0,344.0,23.0,170.0,288.0,148.0,57.0,13.0,1280.0,0
278,Nene,2403,2013-14,53.0,31.0,1560.320,299.0,594.0,1.0,155.0,266.0,65.0,229.0,153.0,117.0,64.0,47.0,754.0,0
377,Kyle Korver,2594,2015-16,80.0,35.0,2400.810,268.0,617.0,158.0,45.0,54.0,14.0,246.0,164.0,98.0,60.0,35.0,739.0,0
1039,Corey Brewer,201147,2013-14,81.0,28.0,2609.350,388.0,807.0,59.0,163.0,227.0,63.0,144.0,135.0,105.0,151.0,30.0,998.0,0
74,Jason Terry,1891,2016-17,74.0,39.0,1364.900,105.0,243.0,73.0,24.0,29.0,15.0,91.0,98.0,36.0,46.0,20.0,307.0,0
2688,Isaiah Whitehead,1627785,2016-17,73.0,22.0,1643.470,204.0,508.0,44.0,91.0,113.0,32.0,152.0,192.0,142.0,42.0,36.0,543.0,0
1697,Blake Griffin,201933,2012-13,80.0,24.0,2598.410,577.0,1072.0,5.0,281.0,426.0,186.0,476.0,299.0,185.0,97.0,50.0,1440.0,0
901,LaMarcus Aldridge,200746,2010-11,81.0,25.0,3211.550,707.0,1415.0,4.0,351.0,444.0,278.0,431.0,170.0,153.0,82.0,94.0,1769.0,0
2661,Buddy Hield,1627741,2016-17,82.0,23.0,1888.210,327.0,767.0,148.0,64.0,76.0,35.0,234.0,121.0,101.0,38.0,9.0,866.0,0
2359,Seth Curry,203552,2016-17,70.0,26.0,2028.850,338.0,703.0,137.0,85.0,100.0,25.0,154.0,189.0,92.0,79.0,7.0,898.0,0
2434,Glenn Robinson III,203922,2015-16,45.0,22.0,508.182,65.0,151.0,14.0,27.0,39.0,12.0,56.0,26.0,18.0,17.0,9.0,171.0,0
413,Matt Barnes,2440,2009-10,81.0,30.0,2097.030,271.0,557.0,66.0,108.0,146.0,106.0,339.0,134.0,112.0,59.0,30.0,716.0,0
530,JR Smith,2747,2007-08,74.0,22.0,1420.720,311.0,674.0,157.0,128.0,178.0,43.0,109.0,128.0,112.0,62.0,12.0,907.0,0
2589,Josh Richardson,1626196,2015-16,52.0,22.0,1106.970,123.0,272.0,53.0,42.0,63.0,21.0,86.0,73.0,35.0,36.0,25.0,341.0,0
1155,Mike Conley,201144,2012-13,80.0,25.0,2756.540,414.0,940.0,106.0,234.0,282.0,43.0,182.0,487.0,189.0,174.0,24.0,1168.0,0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.900,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0,0
2052,Tristan Thompson,202684,2011-12,60.0,21.0,1423.700,194.0,442.0,0.0,106.0,192.0,187.0,202.0,27.0,81.0,27.0,62.0,494.0,0
1087,Joakim Noah,201149,2014-15,67.0,30.0,2048.650,190.0,427.0,0.0,105.0,174.0,219.0,427.0,312.0,123.0,48.0,74.0,485.0,0
1982,Klay Thompson,202691,2013-14,81.0,24.0,2867.820,559.0,1259.0,223.0,147.0,185.0,38.0,211.0,181.0,135.0,74.0,37.0,1488.0,0

In [126]:
df_small['ppg'] = round(df_small['pts'] / df_small['gp'], 1)

In [127]:
df_small

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts,ppg
2577,Jerian Grant,1626170,2015-16,76.0,23.0,1264.890,154.0,391.0,22.0,96.0,123.0,23.0,120.0,177.0,87.0,50.0,10.0,426.0,5.6
100,Jamal Crawford,2037,2008-09,65.0,29.0,2478.300,419.0,1022.0,142.0,300.0,344.0,23.0,170.0,288.0,148.0,57.0,13.0,1280.0,19.7
278,Nene,2403,2013-14,53.0,31.0,1560.320,299.0,594.0,1.0,155.0,266.0,65.0,229.0,153.0,117.0,64.0,47.0,754.0,14.2
377,Kyle Korver,2594,2015-16,80.0,35.0,2400.810,268.0,617.0,158.0,45.0,54.0,14.0,246.0,164.0,98.0,60.0,35.0,739.0,9.2
1039,Corey Brewer,201147,2013-14,81.0,28.0,2609.350,388.0,807.0,59.0,163.0,227.0,63.0,144.0,135.0,105.0,151.0,30.0,998.0,12.3
74,Jason Terry,1891,2016-17,74.0,39.0,1364.900,105.0,243.0,73.0,24.0,29.0,15.0,91.0,98.0,36.0,46.0,20.0,307.0,4.1
2688,Isaiah Whitehead,1627785,2016-17,73.0,22.0,1643.470,204.0,508.0,44.0,91.0,113.0,32.0,152.0,192.0,142.0,42.0,36.0,543.0,7.4
1697,Blake Griffin,201933,2012-13,80.0,24.0,2598.410,577.0,1072.0,5.0,281.0,426.0,186.0,476.0,299.0,185.0,97.0,50.0,1440.0,18.0
901,LaMarcus Aldridge,200746,2010-11,81.0,25.0,3211.550,707.0,1415.0,4.0,351.0,444.0,278.0,431.0,170.0,153.0,82.0,94.0,1769.0,21.8
2661,Buddy Hield,1627741,2016-17,82.0,23.0,1888.210,327.0,767.0,148.0,64.0,76.0,35.0,234.0,121.0,101.0,38.0,9.0,866.0,10.6
2359,Seth Curry,203552,2016-17,70.0,26.0,2028.850,338.0,703.0,137.0,85.0,100.0,25.0,154.0,189.0,92.0,79.0,7.0,898.0,12.8
2434,Glenn Robinson III,203922,2015-16,45.0,22.0,508.182,65.0,151.0,14.0,27.0,39.0,12.0,56.0,26.0,18.0,17.0,9.0,171.0,3.8
413,Matt Barnes,2440,2009-10,81.0,30.0,2097.030,271.0,557.0,66.0,108.0,146.0,106.0,339.0,134.0,112.0,59.0,30.0,716.0,8.8
530,JR Smith,2747,2007-08,74.0,22.0,1420.720,311.0,674.0,157.0,128.0,178.0,43.0,109.0,128.0,112.0,62.0,12.0,907.0,12.3
2589,Josh Richardson,1626196,2015-16,52.0,22.0,1106.970,123.0,272.0,53.0,42.0,63.0,21.0,86.0,73.0,35.0,36.0,25.0,341.0,6.6
1155,Mike Conley,201144,2012-13,80.0,25.0,2756.540,414.0,940.0,106.0,234.0,282.0,43.0,182.0,487.0,189.0,174.0,24.0,1168.0,14.6
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.900,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0,6.0
2052,Tristan Thompson,202684,2011-12,60.0,21.0,1423.700,194.0,442.0,0.0,106.0,192.0,187.0,202.0,27.0,81.0,27.0,62.0,494.0,8.2
1087,Joakim Noah,201149,2014-15,67.0,30.0,2048.650,190.0,427.0,0.0,105.0,174.0,219.0,427.0,312.0,123.0,48.0,74.0,485.0,7.2
1982,Klay Thompson,202691,2013-14,81.0,24.0,2867.820,559.0,1259.0,223.0,147.0,185.0,38.0,211.0,181.0,135.0,74.0,37.0,1488.0,18.4

In [133]:
# insert method, insert to right of the specified column index
df_small.insert(3, column = 'league', value = 'NBA')

ValueError: cannot insert league, already exists

In [134]:
df_small

,player_name,player_id,season_id,league,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts,ppg
2577,Jerian Grant,1626170,2015-16,NBA,76.0,23.0,1264.890,154.0,391.0,22.0,96.0,123.0,23.0,120.0,177.0,87.0,50.0,10.0,426.0,5.6
100,Jamal Crawford,2037,2008-09,NBA,65.0,29.0,2478.300,419.0,1022.0,142.0,300.0,344.0,23.0,170.0,288.0,148.0,57.0,13.0,1280.0,19.7
278,Nene,2403,2013-14,NBA,53.0,31.0,1560.320,299.0,594.0,1.0,155.0,266.0,65.0,229.0,153.0,117.0,64.0,47.0,754.0,14.2
377,Kyle Korver,2594,2015-16,NBA,80.0,35.0,2400.810,268.0,617.0,158.0,45.0,54.0,14.0,246.0,164.0,98.0,60.0,35.0,739.0,9.2
1039,Corey Brewer,201147,2013-14,NBA,81.0,28.0,2609.350,388.0,807.0,59.0,163.0,227.0,63.0,144.0,135.0,105.0,151.0,30.0,998.0,12.3
74,Jason Terry,1891,2016-17,NBA,74.0,39.0,1364.900,105.0,243.0,73.0,24.0,29.0,15.0,91.0,98.0,36.0,46.0,20.0,307.0,4.1
2688,Isaiah Whitehead,1627785,2016-17,NBA,73.0,22.0,1643.470,204.0,508.0,44.0,91.0,113.0,32.0,152.0,192.0,142.0,42.0,36.0,543.0,7.4
1697,Blake Griffin,201933,2012-13,NBA,80.0,24.0,2598.410,577.0,1072.0,5.0,281.0,426.0,186.0,476.0,299.0,185.0,97.0,50.0,1440.0,18.0
901,LaMarcus Aldridge,200746,2010-11,NBA,81.0,25.0,3211.550,707.0,1415.0,4.0,351.0,444.0,278.0,431.0,170.0,153.0,82.0,94.0,1769.0,21.8
2661,Buddy Hield,1627741,2016-17,NBA,82.0,23.0,1888.210,327.0,767.0,148.0,64.0,76.0,35.0,234.0,121.0,101.0,38.0,9.0,866.0,10.6
2359,Seth Curry,203552,2016-17,NBA,70.0,26.0,2028.850,338.0,703.0,137.0,85.0,100.0,25.0,154.0,189.0,92.0,79.0,7.0,898.0,12.8
2434,Glenn Robinson III,203922,2015-16,NBA,45.0,22.0,508.182,65.0,151.0,14.0,27.0,39.0,12.0,56.0,26.0,18.0,17.0,9.0,171.0,3.8
413,Matt Barnes,2440,2009-10,NBA,81.0,30.0,2097.030,271.0,557.0,66.0,108.0,146.0,106.0,339.0,134.0,112.0,59.0,30.0,716.0,8.8
530,JR Smith,2747,2007-08,NBA,74.0,22.0,1420.720,311.0,674.0,157.0,128.0,178.0,43.0,109.0,128.0,112.0,62.0,12.0,907.0,12.3
2589,Josh Richardson,1626196,2015-16,NBA,52.0,22.0,1106.970,123.0,272.0,53.0,42.0,63.0,21.0,86.0,73.0,35.0,36.0,25.0,341.0,6.6
1155,Mike Conley,201144,2012-13,NBA,80.0,25.0,2756.540,414.0,940.0,106.0,234.0,282.0,43.0,182.0,487.0,189.0,174.0,24.0,1168.0,14.6
1198,Spencer Hawes,201150,2015-16,NBA,57.0,28.0,1034.900,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0,6.0
2052,Tristan Thompson,202684,2011-12,NBA,60.0,21.0,1423.700,194.0,442.0,0.0,106.0,192.0,187.0,202.0,27.0,81.0,27.0,62.0,494.0,8.2
1087,Joakim Noah,201149,2014-15,NBA,67.0,30.0,2048.650,190.0,427.0,0.0,105.0,174.0,219.0,427.0,312.0,123.0,48.0,74.0,485.0,7.2
1982,Klay Thompson,202691,2013-14,NBA,81.0,24.0,2867.820,559.0,1259.0,223.0,147.0,185.0,38.0,211.0,181.0,135.0,74.0,37.0,1488.0,18.4

In [135]:
# drop a column
df_small.drop('league', axis=1)

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts,ppg
2577,Jerian Grant,1626170,2015-16,76.0,23.0,1264.890,154.0,391.0,22.0,96.0,123.0,23.0,120.0,177.0,87.0,50.0,10.0,426.0,5.6
100,Jamal Crawford,2037,2008-09,65.0,29.0,2478.300,419.0,1022.0,142.0,300.0,344.0,23.0,170.0,288.0,148.0,57.0,13.0,1280.0,19.7
278,Nene,2403,2013-14,53.0,31.0,1560.320,299.0,594.0,1.0,155.0,266.0,65.0,229.0,153.0,117.0,64.0,47.0,754.0,14.2
377,Kyle Korver,2594,2015-16,80.0,35.0,2400.810,268.0,617.0,158.0,45.0,54.0,14.0,246.0,164.0,98.0,60.0,35.0,739.0,9.2
1039,Corey Brewer,201147,2013-14,81.0,28.0,2609.350,388.0,807.0,59.0,163.0,227.0,63.0,144.0,135.0,105.0,151.0,30.0,998.0,12.3
74,Jason Terry,1891,2016-17,74.0,39.0,1364.900,105.0,243.0,73.0,24.0,29.0,15.0,91.0,98.0,36.0,46.0,20.0,307.0,4.1
2688,Isaiah Whitehead,1627785,2016-17,73.0,22.0,1643.470,204.0,508.0,44.0,91.0,113.0,32.0,152.0,192.0,142.0,42.0,36.0,543.0,7.4
1697,Blake Griffin,201933,2012-13,80.0,24.0,2598.410,577.0,1072.0,5.0,281.0,426.0,186.0,476.0,299.0,185.0,97.0,50.0,1440.0,18.0
901,LaMarcus Aldridge,200746,2010-11,81.0,25.0,3211.550,707.0,1415.0,4.0,351.0,444.0,278.0,431.0,170.0,153.0,82.0,94.0,1769.0,21.8
2661,Buddy Hield,1627741,2016-17,82.0,23.0,1888.210,327.0,767.0,148.0,64.0,76.0,35.0,234.0,121.0,101.0,38.0,9.0,866.0,10.6
2359,Seth Curry,203552,2016-17,70.0,26.0,2028.850,338.0,703.0,137.0,85.0,100.0,25.0,154.0,189.0,92.0,79.0,7.0,898.0,12.8
2434,Glenn Robinson III,203922,2015-16,45.0,22.0,508.182,65.0,151.0,14.0,27.0,39.0,12.0,56.0,26.0,18.0,17.0,9.0,171.0,3.8
413,Matt Barnes,2440,2009-10,81.0,30.0,2097.030,271.0,557.0,66.0,108.0,146.0,106.0,339.0,134.0,112.0,59.0,30.0,716.0,8.8
530,JR Smith,2747,2007-08,74.0,22.0,1420.720,311.0,674.0,157.0,128.0,178.0,43.0,109.0,128.0,112.0,62.0,12.0,907.0,12.3
2589,Josh Richardson,1626196,2015-16,52.0,22.0,1106.970,123.0,272.0,53.0,42.0,63.0,21.0,86.0,73.0,35.0,36.0,25.0,341.0,6.6
1155,Mike Conley,201144,2012-13,80.0,25.0,2756.540,414.0,940.0,106.0,234.0,282.0,43.0,182.0,487.0,189.0,174.0,24.0,1168.0,14.6
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.900,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0,6.0
2052,Tristan Thompson,202684,2011-12,60.0,21.0,1423.700,194.0,442.0,0.0,106.0,192.0,187.0,202.0,27.0,81.0,27.0,62.0,494.0,8.2
1087,Joakim Noah,201149,2014-15,67.0,30.0,2048.650,190.0,427.0,0.0,105.0,174.0,219.0,427.0,312.0,123.0,48.0,74.0,485.0,7.2
1982,Klay Thompson,202691,2013-14,81.0,24.0,2867.820,559.0,1259.0,223.0,147.0,185.0,38.0,211.0,181.0,135.0,74.0,37.0,1488.0,18.4

In [151]:
# copy a dataframe with specified columns
rebound_df = df_small[['player_name', 'oreb', 'dreb']]

In [153]:
rebound_df

             player_name   oreb   dreb
493           Beno Udrih   38.0  181.0
1338        Goran Dragic   60.0  178.0
64           Jason Terry   41.0  190.0
970          Steve Novak    8.0   50.0
238        Manu Ginobili   86.0  258.0
2103  Donatas Motiejunas   36.0   57.0
509         Devin Harris    6.0  110.0
2606     Larry Nance Jr.  120.0  249.0
801      Marvin Williams  106.0  310.0
1819       Larry Sanders  224.0  448.0
1453       Ryan Anderson  129.0  226.0
1741         Evan Turner   40.0  377.0
2739   Willy Hernangomez  170.0  332.0
1821       Larry Sanders   67.0   99.0
2684       Georges Niang    2.0   15.0
2659       Brice Johnson    1.0    2.0
1505       DeMar DeRozan   41.0  236.0
269                 Nene  104.0  221.0
1198       Spencer Hawes   51.0  193.0
1954           Jon Leuer   13.0   24.0

# renaming dataframe columns

In [161]:
df = df_small[['player_name', 'gp', 'pts']]
df.columns = ['player_name', 'games_played', 'total_points']
df

             player_name  games_played  total_points
493           Beno Udrih          79.0        1023.0
1338        Goran Dragic          77.0        1134.0
64           Jason Terry          81.0        1350.0
970          Steve Novak          54.0         178.0
238        Manu Ginobili          77.0         987.0
2103  Donatas Motiejunas          44.0         250.0
509         Devin Harris          58.0         577.0
2606     Larry Nance Jr.          63.0         449.0
801      Marvin Williams          81.0         820.0
1819       Larry Sanders          71.0         696.0
1453       Ryan Anderson          64.0         681.0
1741         Evan Turner          82.0         779.0
2739   Willy Hernangomez          72.0         587.0
1821       Larry Sanders          27.0         196.0
2684       Georges Niang          23.0          21.0
2659       Brice Johnson           3.0           4.0
1505       DeMar DeRozan          60.0        1204.0
269                 Nene          55.0         528.0
1198       Spencer Hawes          57.0         340.0
1954           Jon Leuer          28.0          56.0

In [162]:
# or using the Panda's rename method
df.rename(columns={
    'games_played': 'total_games_played',
    'total_points': 'total_points_scored'
})

             player_name  total_games_played  total_points_scored
493           Beno Udrih                79.0               1023.0
1338        Goran Dragic                77.0               1134.0
64           Jason Terry                81.0               1350.0
970          Steve Novak                54.0                178.0
238        Manu Ginobili                77.0                987.0
2103  Donatas Motiejunas                44.0                250.0
509         Devin Harris                58.0                577.0
2606     Larry Nance Jr.                63.0                449.0
801      Marvin Williams                81.0                820.0
1819       Larry Sanders                71.0                696.0
1453       Ryan Anderson                64.0                681.0
1741         Evan Turner                82.0                779.0
2739   Willy Hernangomez                72.0                587.0
1821       Larry Sanders                27.0                196.0
2684       Georges Niang                23.0                 21.0
2659       Brice Johnson                 3.0                  4.0
1505       DeMar DeRozan                60.0               1204.0
269                 Nene                55.0                528.0
1198       Spencer Hawes                57.0                340.0
1954           Jon Leuer                28.0                 56.0

In [167]:
# selecting rows
df_subset = df_small.sample(10)
df_subset

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
1954,Jon Leuer,202720,2012-13,28.0,24.0,186.54200,25.0,52.0,0.0,6.0,13.0,13.0,24.0,8.0,8.0,6.0,0.0,56.0
2606,Larry Nance Jr.,1626204,2016-17,63.0,24.0,1441.84000,190.0,361.0,10.0,59.0,80.0,120.0,249.0,96.0,56.0,82.0,39.0,449.0
2739,Willy Hernangomez,1626195,2016-17,72.0,22.0,1324.39000,246.0,465.0,4.0,91.0,125.0,170.0,332.0,96.0,100.0,41.0,36.0,587.0
269,Nene,2403,2004-05,55.0,22.0,1315.39000,194.0,386.0,0.0,140.0,212.0,104.0,221.0,84.0,94.0,50.0,48.0,528.0
2103,Donatas Motiejunas,202700,2012-13,44.0,22.0,537.29200,97.0,213.0,24.0,32.0,51.0,36.0,57.0,31.0,37.0,7.0,10.0,250.0
2659,Brice Johnson,1627744,2016-17,3.0,22.0,9.21667,2.0,7.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0
1821,Larry Sanders,202336,2014-15,27.0,26.0,585.52800,86.0,172.0,0.0,24.0,48.0,67.0,99.0,23.0,28.0,26.0,39.0,196.0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.90000,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0
1505,DeMar DeRozan,201942,2014-15,60.0,25.0,2100.30000,409.0,990.0,25.0,361.0,434.0,41.0,236.0,210.0,137.0,73.0,11.0,1204.0
801,Marvin Williams,101107,2009-10,81.0,24.0,2468.49000,302.0,664.0,40.0,176.0,215.0,106.0,310.0,93.0,72.0,66.0,46.0,820.0

In [173]:
# select the 4th row
df_subset.iloc[4]

player_name    Donatas Motiejunas
player_id                  202700
season_id                 2012-13
gp                             44
age                            22
min                       537.292
fgm                            97
fga                           213
fg3m                           24
ftm                            32
fta                            51
oreb                           36
dreb                           57
ast                            31
tov                            37
stl                             7
blk                            10
pts                           250
Name: 2103, dtype: object

In [174]:
# skip the 1st row, taking the next 10
df_subset.iloc[1:11]

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
2606,Larry Nance Jr.,1626204,2016-17,63.0,24.0,1441.84000,190.0,361.0,10.0,59.0,80.0,120.0,249.0,96.0,56.0,82.0,39.0,449.0
2739,Willy Hernangomez,1626195,2016-17,72.0,22.0,1324.39000,246.0,465.0,4.0,91.0,125.0,170.0,332.0,96.0,100.0,41.0,36.0,587.0
269,Nene,2403,2004-05,55.0,22.0,1315.39000,194.0,386.0,0.0,140.0,212.0,104.0,221.0,84.0,94.0,50.0,48.0,528.0
2103,Donatas Motiejunas,202700,2012-13,44.0,22.0,537.29200,97.0,213.0,24.0,32.0,51.0,36.0,57.0,31.0,37.0,7.0,10.0,250.0
2659,Brice Johnson,1627744,2016-17,3.0,22.0,9.21667,2.0,7.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0
1821,Larry Sanders,202336,2014-15,27.0,26.0,585.52800,86.0,172.0,0.0,24.0,48.0,67.0,99.0,23.0,28.0,26.0,39.0,196.0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.90000,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0
1505,DeMar DeRozan,201942,2014-15,60.0,25.0,2100.30000,409.0,990.0,25.0,361.0,434.0,41.0,236.0,210.0,137.0,73.0,11.0,1204.0
801,Marvin Williams,101107,2009-10,81.0,24.0,2468.49000,302.0,664.0,40.0,176.0,215.0,106.0,310.0,93.0,72.0,66.0,46.0,820.0

In [189]:
celtics_dict = {'first_name': ['Kristaps', 'Al', 'Derrick', 'Jayson', 'Jaylen', np.nan], 
        'last_name': ['Porzingis', 'Horford', 'White', 'Tatum', 'Brown', np.nan], 
        'ppg': [27.4, 18.7, 9.9, 18.3, 7.8, np.nan], 
        'apg': [8.3, 2.5, 5.4, 3.0, 1.4, np.nan],
        'rpg': [8.5, 5.5, 5.3, 5.1, 3.7, np.nan],
        'blks': [2.3, 1.5, 1.7, 0.5, np.nan, np.nan]}
df_celtics = pd.DataFrame(celtics_dict, index=['C','PF','PG','SF','SG', np.nan])

In [177]:
df_celtics

   first_name  last_name   ppg  apg  rpg
C    Kristaps  Porzingis  27.4  8.3  8.5
PF         Al    Horford  18.7  2.5  5.5
PG    Derrick      White   9.9  5.4  5.3
SF     Jayson      Tatum  18.3  3.0  5.1
SG     Jaylen      Brown   7.8  1.4  3.7

In [180]:
df_celtics.loc['SF']

first_name    Jayson
last_name      Tatum
ppg             18.3
apg                3
rpg              5.1
Name: SF, dtype: object

In [182]:
df_celtics.loc[['SF', 'SG']]

   first_name last_name   ppg  apg  rpg
SF     Jayson     Tatum  18.3  3.0  5.1
SG     Jaylen     Brown   7.8  1.4  3.7

# Cleaning Data 
# adding and dropping rows

In [190]:
df_celtics

    first_name  last_name   ppg  apg  rpg  blks
C     Kristaps  Porzingis  27.4  8.3  8.5   2.3
PF          Al    Horford  18.7  2.5  5.5   1.5
PG     Derrick      White   9.9  5.4  5.3   1.7
SF      Jayson      Tatum  18.3  3.0  5.1   0.5
SG      Jaylen      Brown   7.8  1.4  3.7   NaN
NaN        NaN        NaN   NaN  NaN  NaN   NaN

In [191]:
# dropping using the dropna method, axis = 0 for rows, axis = 1 for cols

In [194]:
# remove rows with any NaN values
clean_df = df_celtics.dropna(axis=0, how='any')

In [195]:
clean_df

   first_name  last_name   ppg  apg  rpg  blks
C    Kristaps  Porzingis  27.4  8.3  8.5   2.3
PF         Al    Horford  18.7  2.5  5.5   1.5
PG    Derrick      White   9.9  5.4  5.3   1.7
SF     Jayson      Tatum  18.3  3.0  5.1   0.5

In [196]:
# only drop rows with all NaN values
clean_df_all = df_celtics.dropna(axis=0, how='all')

In [197]:
clean_df_all

   first_name  last_name   ppg  apg  rpg  blks
C    Kristaps  Porzingis  27.4  8.3  8.5   2.3
PF         Al    Horford  18.7  2.5  5.5   1.5
PG    Derrick      White   9.9  5.4  5.3   1.7
SF     Jayson      Tatum  18.3  3.0  5.1   0.5
SG     Jaylen      Brown   7.8  1.4  3.7   NaN

In [198]:
# drop any rows with NaN in the blks column

In [199]:
clean_blks = df_celtics.dropna(subset=['blks'])

In [200]:
clean_blks

   first_name  last_name   ppg  apg  rpg  blks
C    Kristaps  Porzingis  27.4  8.3  8.5   2.3
PF         Al    Horford  18.7  2.5  5.5   1.5
PG    Derrick      White   9.9  5.4  5.3   1.7
SF     Jayson      Tatum  18.3  3.0  5.1   0.5

In [201]:
# fill NaN values with proper values using fillna

In [202]:
filled_df = df_celtics.fillna(0)

In [203]:
filled_df

    first_name  last_name   ppg  apg  rpg  blks
C     Kristaps  Porzingis  27.4  8.3  8.5   2.3
PF          Al    Horford  18.7  2.5  5.5   1.5
PG     Derrick      White   9.9  5.4  5.3   1.7
SF      Jayson      Tatum  18.3  3.0  5.1   0.5
SG      Jaylen      Brown   7.8  1.4  3.7   0.0
NaN          0          0   0.0  0.0  0.0   0.0

In [ ]:
# appending data frames

In [204]:
df1 = pd.DataFrame({'first_name': ['Kristaps', 'Al', 'Derrick', 'Jayson', 'Jaylen'], 
        'last_name': ['Porzingis', 'Horford', 'White', 'Tatum', 'Brown'], 
        'ppg': [27.4, 18.7, 9.9, 18.3, 7.8], 
        'apg': [8.3, 2.5, 5.4, 3.0, 1.4],
        'rpg': [8.5, 5.5, 5.3, 5.1, 3.7]})

In [205]:
df2 = pd.DataFrame({'first_name': ['Malcolm', 'Payton'], 
        'last_name': ['Brogdon', 'Pritchard'], 
        'ppg': [17.4, 6.7], 
        'apg': [5.3, 2.5],
        'rpg': [3.5, 2.5]})

In [206]:
df_combined = df1.append(df2)

In [207]:
df_combined

  first_name  last_name   ppg  apg  rpg
0   Kristaps  Porzingis  27.4  8.3  8.5
1         Al    Horford  18.7  2.5  5.5
2    Derrick      White   9.9  5.4  5.3
3     Jayson      Tatum  18.3  3.0  5.1
4     Jaylen      Brown   7.8  1.4  3.7
0    Malcolm    Brogdon  17.4  5.3  3.5
1     Payton  Pritchard   6.7  2.5  2.5

# inplace parameter
# asks if you want to override the existing dataframe

In [209]:
df_small

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
493,Beno Udrih,2757,2009-10,79.0,27.0,2476.67000,415.0,841.0,75.0,118.0,141.0,38.0,181.0,372.0,136.0,89.0,10.0,1023.0
1338,Goran Dragic,201609,2012-13,77.0,27.0,2581.21000,401.0,906.0,88.0,244.0,326.0,60.0,178.0,569.0,212.0,124.0,26.0,1134.0
64,Jason Terry,1891,2006-07,81.0,29.0,2846.12000,514.0,1063.0,162.0,160.0,199.0,41.0,190.0,422.0,152.0,81.0,17.0,1350.0
970,Steve Novak,200779,2013-14,54.0,31.0,540.37500,60.0,146.0,52.0,6.0,6.0,8.0,50.0,13.0,5.0,12.0,4.0,178.0
238,Manu Ginobili,1938,2003-04,77.0,26.0,2254.65000,330.0,789.0,88.0,239.0,298.0,86.0,258.0,291.0,161.0,136.0,16.0,987.0
2103,Donatas Motiejunas,202700,2012-13,44.0,22.0,537.29200,97.0,213.0,24.0,32.0,51.0,36.0,57.0,31.0,37.0,7.0,10.0,250.0
509,Devin Harris,2734,2012-13,58.0,30.0,1421.33000,194.0,443.0,77.0,112.0,154.0,6.0,110.0,197.0,88.0,64.0,13.0,577.0
2606,Larry Nance Jr.,1626204,2016-17,63.0,24.0,1441.84000,190.0,361.0,10.0,59.0,80.0,120.0,249.0,96.0,56.0,82.0,39.0,449.0
801,Marvin Williams,101107,2009-10,81.0,24.0,2468.49000,302.0,664.0,40.0,176.0,215.0,106.0,310.0,93.0,72.0,66.0,46.0,820.0
1819,Larry Sanders,202336,2012-13,71.0,24.0,1937.45000,306.0,605.0,0.0,84.0,136.0,224.0,448.0,83.0,87.0,53.0,201.0,696.0
1453,Ryan Anderson,201583,2010-11,64.0,23.0,1424.58000,226.0,525.0,134.0,95.0,117.0,129.0,226.0,52.0,49.0,30.0,38.0,681.0
1741,Evan Turner,202323,2014-15,82.0,26.0,2259.83000,320.0,746.0,33.0,106.0,141.0,40.0,377.0,449.0,198.0,83.0,19.0,779.0
2739,Willy Hernangomez,1626195,2016-17,72.0,22.0,1324.39000,246.0,465.0,4.0,91.0,125.0,170.0,332.0,96.0,100.0,41.0,36.0,587.0
1821,Larry Sanders,202336,2014-15,27.0,26.0,585.52800,86.0,172.0,0.0,24.0,48.0,67.0,99.0,23.0,28.0,26.0,39.0,196.0
2684,Georges Niang,1627777,2016-17,23.0,23.0,92.73170,9.0,36.0,1.0,2.0,2.0,2.0,15.0,5.0,5.0,3.0,0.0,21.0
2659,Brice Johnson,1627744,2016-17,3.0,22.0,9.21667,2.0,7.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0
1505,DeMar DeRozan,201942,2014-15,60.0,25.0,2100.30000,409.0,990.0,25.0,361.0,434.0,41.0,236.0,210.0,137.0,73.0,11.0,1204.0
269,Nene,2403,2004-05,55.0,22.0,1315.39000,194.0,386.0,0.0,140.0,212.0,104.0,221.0,84.0,94.0,50.0,48.0,528.0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.90000,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0
1954,Jon Leuer,202720,2012-13,28.0,24.0,186.54200,25.0,52.0,0.0,6.0,13.0,13.0,24.0,8.0,8.0,6.0,0.0,56.0

In [211]:
# sort the values by games played, but the original df_small is not affected
df_small.sort_values('gp')

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
2659,Brice Johnson,1627744,2016-17,3.0,22.0,9.21667,2.0,7.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0
2684,Georges Niang,1627777,2016-17,23.0,23.0,92.73170,9.0,36.0,1.0,2.0,2.0,2.0,15.0,5.0,5.0,3.0,0.0,21.0
1821,Larry Sanders,202336,2014-15,27.0,26.0,585.52800,86.0,172.0,0.0,24.0,48.0,67.0,99.0,23.0,28.0,26.0,39.0,196.0
1954,Jon Leuer,202720,2012-13,28.0,24.0,186.54200,25.0,52.0,0.0,6.0,13.0,13.0,24.0,8.0,8.0,6.0,0.0,56.0
2103,Donatas Motiejunas,202700,2012-13,44.0,22.0,537.29200,97.0,213.0,24.0,32.0,51.0,36.0,57.0,31.0,37.0,7.0,10.0,250.0
970,Steve Novak,200779,2013-14,54.0,31.0,540.37500,60.0,146.0,52.0,6.0,6.0,8.0,50.0,13.0,5.0,12.0,4.0,178.0
269,Nene,2403,2004-05,55.0,22.0,1315.39000,194.0,386.0,0.0,140.0,212.0,104.0,221.0,84.0,94.0,50.0,48.0,528.0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.90000,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0
509,Devin Harris,2734,2012-13,58.0,30.0,1421.33000,194.0,443.0,77.0,112.0,154.0,6.0,110.0,197.0,88.0,64.0,13.0,577.0
1505,DeMar DeRozan,201942,2014-15,60.0,25.0,2100.30000,409.0,990.0,25.0,361.0,434.0,41.0,236.0,210.0,137.0,73.0,11.0,1204.0
2606,Larry Nance Jr.,1626204,2016-17,63.0,24.0,1441.84000,190.0,361.0,10.0,59.0,80.0,120.0,249.0,96.0,56.0,82.0,39.0,449.0
1453,Ryan Anderson,201583,2010-11,64.0,23.0,1424.58000,226.0,525.0,134.0,95.0,117.0,129.0,226.0,52.0,49.0,30.0,38.0,681.0
1819,Larry Sanders,202336,2012-13,71.0,24.0,1937.45000,306.0,605.0,0.0,84.0,136.0,224.0,448.0,83.0,87.0,53.0,201.0,696.0
2739,Willy Hernangomez,1626195,2016-17,72.0,22.0,1324.39000,246.0,465.0,4.0,91.0,125.0,170.0,332.0,96.0,100.0,41.0,36.0,587.0
238,Manu Ginobili,1938,2003-04,77.0,26.0,2254.65000,330.0,789.0,88.0,239.0,298.0,86.0,258.0,291.0,161.0,136.0,16.0,987.0
1338,Goran Dragic,201609,2012-13,77.0,27.0,2581.21000,401.0,906.0,88.0,244.0,326.0,60.0,178.0,569.0,212.0,124.0,26.0,1134.0
493,Beno Udrih,2757,2009-10,79.0,27.0,2476.67000,415.0,841.0,75.0,118.0,141.0,38.0,181.0,372.0,136.0,89.0,10.0,1023.0
801,Marvin Williams,101107,2009-10,81.0,24.0,2468.49000,302.0,664.0,40.0,176.0,215.0,106.0,310.0,93.0,72.0,66.0,46.0,820.0
64,Jason Terry,1891,2006-07,81.0,29.0,2846.12000,514.0,1063.0,162.0,160.0,199.0,41.0,190.0,422.0,152.0,81.0,17.0,1350.0
1741,Evan Turner,202323,2014-15,82.0,26.0,2259.83000,320.0,746.0,33.0,106.0,141.0,40.0,377.0,449.0,198.0,83.0,19.0,779.0

In [214]:
# set the inplace parameter, will modify the original dataframe inplace
# df_small will now be sorted by games played
df_small.sort_values('gp', inplace = True)

In [215]:
df_small

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
2659,Brice Johnson,1627744,2016-17,3.0,22.0,9.21667,2.0,7.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0
2684,Georges Niang,1627777,2016-17,23.0,23.0,92.73170,9.0,36.0,1.0,2.0,2.0,2.0,15.0,5.0,5.0,3.0,0.0,21.0
1821,Larry Sanders,202336,2014-15,27.0,26.0,585.52800,86.0,172.0,0.0,24.0,48.0,67.0,99.0,23.0,28.0,26.0,39.0,196.0
1954,Jon Leuer,202720,2012-13,28.0,24.0,186.54200,25.0,52.0,0.0,6.0,13.0,13.0,24.0,8.0,8.0,6.0,0.0,56.0
2103,Donatas Motiejunas,202700,2012-13,44.0,22.0,537.29200,97.0,213.0,24.0,32.0,51.0,36.0,57.0,31.0,37.0,7.0,10.0,250.0
970,Steve Novak,200779,2013-14,54.0,31.0,540.37500,60.0,146.0,52.0,6.0,6.0,8.0,50.0,13.0,5.0,12.0,4.0,178.0
269,Nene,2403,2004-05,55.0,22.0,1315.39000,194.0,386.0,0.0,140.0,212.0,104.0,221.0,84.0,94.0,50.0,48.0,528.0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.90000,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0
509,Devin Harris,2734,2012-13,58.0,30.0,1421.33000,194.0,443.0,77.0,112.0,154.0,6.0,110.0,197.0,88.0,64.0,13.0,577.0
1505,DeMar DeRozan,201942,2014-15,60.0,25.0,2100.30000,409.0,990.0,25.0,361.0,434.0,41.0,236.0,210.0,137.0,73.0,11.0,1204.0
2606,Larry Nance Jr.,1626204,2016-17,63.0,24.0,1441.84000,190.0,361.0,10.0,59.0,80.0,120.0,249.0,96.0,56.0,82.0,39.0,449.0
1453,Ryan Anderson,201583,2010-11,64.0,23.0,1424.58000,226.0,525.0,134.0,95.0,117.0,129.0,226.0,52.0,49.0,30.0,38.0,681.0
1819,Larry Sanders,202336,2012-13,71.0,24.0,1937.45000,306.0,605.0,0.0,84.0,136.0,224.0,448.0,83.0,87.0,53.0,201.0,696.0
2739,Willy Hernangomez,1626195,2016-17,72.0,22.0,1324.39000,246.0,465.0,4.0,91.0,125.0,170.0,332.0,96.0,100.0,41.0,36.0,587.0
238,Manu Ginobili,1938,2003-04,77.0,26.0,2254.65000,330.0,789.0,88.0,239.0,298.0,86.0,258.0,291.0,161.0,136.0,16.0,987.0
1338,Goran Dragic,201609,2012-13,77.0,27.0,2581.21000,401.0,906.0,88.0,244.0,326.0,60.0,178.0,569.0,212.0,124.0,26.0,1134.0
493,Beno Udrih,2757,2009-10,79.0,27.0,2476.67000,415.0,841.0,75.0,118.0,141.0,38.0,181.0,372.0,136.0,89.0,10.0,1023.0
801,Marvin Williams,101107,2009-10,81.0,24.0,2468.49000,302.0,664.0,40.0,176.0,215.0,106.0,310.0,93.0,72.0,66.0,46.0,820.0
64,Jason Terry,1891,2006-07,81.0,29.0,2846.12000,514.0,1063.0,162.0,160.0,199.0,41.0,190.0,422.0,152.0,81.0,17.0,1350.0
1741,Evan Turner,202323,2014-15,82.0,26.0,2259.83000,320.0,746.0,33.0,106.0,141.0,40.0,377.0,449.0,198.0,83.0,19.0,779.0

In [216]:
# use inplace = False to not lose the original dataframe
# assign the result to a new variable
df_points = df_small.sort_values('pts', inplace = False)

In [217]:
df_points

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
2659,Brice Johnson,1627744,2016-17,3.0,22.0,9.21667,2.0,7.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0
2684,Georges Niang,1627777,2016-17,23.0,23.0,92.73170,9.0,36.0,1.0,2.0,2.0,2.0,15.0,5.0,5.0,3.0,0.0,21.0
1954,Jon Leuer,202720,2012-13,28.0,24.0,186.54200,25.0,52.0,0.0,6.0,13.0,13.0,24.0,8.0,8.0,6.0,0.0,56.0
970,Steve Novak,200779,2013-14,54.0,31.0,540.37500,60.0,146.0,52.0,6.0,6.0,8.0,50.0,13.0,5.0,12.0,4.0,178.0
1821,Larry Sanders,202336,2014-15,27.0,26.0,585.52800,86.0,172.0,0.0,24.0,48.0,67.0,99.0,23.0,28.0,26.0,39.0,196.0
2103,Donatas Motiejunas,202700,2012-13,44.0,22.0,537.29200,97.0,213.0,24.0,32.0,51.0,36.0,57.0,31.0,37.0,7.0,10.0,250.0
1198,Spencer Hawes,201150,2015-16,57.0,28.0,1034.90000,124.0,306.0,38.0,54.0,65.0,51.0,193.0,109.0,58.0,22.0,27.0,340.0
2606,Larry Nance Jr.,1626204,2016-17,63.0,24.0,1441.84000,190.0,361.0,10.0,59.0,80.0,120.0,249.0,96.0,56.0,82.0,39.0,449.0
269,Nene,2403,2004-05,55.0,22.0,1315.39000,194.0,386.0,0.0,140.0,212.0,104.0,221.0,84.0,94.0,50.0,48.0,528.0
509,Devin Harris,2734,2012-13,58.0,30.0,1421.33000,194.0,443.0,77.0,112.0,154.0,6.0,110.0,197.0,88.0,64.0,13.0,577.0
2739,Willy Hernangomez,1626195,2016-17,72.0,22.0,1324.39000,246.0,465.0,4.0,91.0,125.0,170.0,332.0,96.0,100.0,41.0,36.0,587.0
1453,Ryan Anderson,201583,2010-11,64.0,23.0,1424.58000,226.0,525.0,134.0,95.0,117.0,129.0,226.0,52.0,49.0,30.0,38.0,681.0
1819,Larry Sanders,202336,2012-13,71.0,24.0,1937.45000,306.0,605.0,0.0,84.0,136.0,224.0,448.0,83.0,87.0,53.0,201.0,696.0
1741,Evan Turner,202323,2014-15,82.0,26.0,2259.83000,320.0,746.0,33.0,106.0,141.0,40.0,377.0,449.0,198.0,83.0,19.0,779.0
801,Marvin Williams,101107,2009-10,81.0,24.0,2468.49000,302.0,664.0,40.0,176.0,215.0,106.0,310.0,93.0,72.0,66.0,46.0,820.0
238,Manu Ginobili,1938,2003-04,77.0,26.0,2254.65000,330.0,789.0,88.0,239.0,298.0,86.0,258.0,291.0,161.0,136.0,16.0,987.0
493,Beno Udrih,2757,2009-10,79.0,27.0,2476.67000,415.0,841.0,75.0,118.0,141.0,38.0,181.0,372.0,136.0,89.0,10.0,1023.0
1338,Goran Dragic,201609,2012-13,77.0,27.0,2581.21000,401.0,906.0,88.0,244.0,326.0,60.0,178.0,569.0,212.0,124.0,26.0,1134.0
1505,DeMar DeRozan,201942,2014-15,60.0,25.0,2100.30000,409.0,990.0,25.0,361.0,434.0,41.0,236.0,210.0,137.0,73.0,11.0,1204.0
64,Jason Terry,1891,2006-07,81.0,29.0,2846.12000,514.0,1063.0,162.0,160.0,199.0,41.0,190.0,422.0,152.0,81.0,17.0,1350.0

# Sorting Data Frames

In [236]:
celtics_dict = {'first_name': ['Kristaps', 'Al', 'Derrick', 'Jayson', 'Jaylen'], 
        'last_name': ['Porzingis', 'Horford', 'White', 'Tatum', 'Brown'], 
        'ppg': [27.4, 18.7, 9.9, 18.7, 7.8], 
        'apg': [8.3, 2.5, 5.4, 3.0, 1.4],
        'rpg': [8.5, 5.5, 5.3, 5.1, 3.7]}
unsorted_celtics_df = pd.DataFrame(celtics_dict, index=[1,4,3,2,0])
unsorted_celtics_df

  first_name  last_name   ppg  apg  rpg
1   Kristaps  Porzingis  27.4  8.3  8.5
4         Al    Horford  18.7  2.5  5.5
3    Derrick      White   9.9  5.4  5.3
2     Jayson      Tatum  18.7  3.0  5.1
0     Jaylen      Brown   7.8  1.4  3.7

In [237]:
# sort the index numbers using the sort_index method
sorted_celtics_df = unsorted_celtics_df.sort_index()
sorted_celtics_df

  first_name  last_name   ppg  apg  rpg
0     Jaylen      Brown   7.8  1.4  3.7
1   Kristaps  Porzingis  27.4  8.3  8.5
2     Jayson      Tatum  18.7  3.0  5.1
3    Derrick      White   9.9  5.4  5.3
4         Al    Horford  18.7  2.5  5.5

In [238]:
# sort by values in a data frame's column
sorted_by_ppg = sorted_celtics_df.sort_values('ppg')
sorted_by_ppg

  first_name  last_name   ppg  apg  rpg
0     Jaylen      Brown   7.8  1.4  3.7
3    Derrick      White   9.9  5.4  5.3
2     Jayson      Tatum  18.7  3.0  5.1
4         Al    Horford  18.7  2.5  5.5
1   Kristaps  Porzingis  27.4  8.3  8.5

In [239]:
descending_pgg = sorted_celtics_df.sort_values('ppg', ascending=False)
descending_pgg

  first_name  last_name   ppg  apg  rpg
1   Kristaps  Porzingis  27.4  8.3  8.5
2     Jayson      Tatum  18.7  3.0  5.1
4         Al    Horford  18.7  2.5  5.5
3    Derrick      White   9.9  5.4  5.3
0     Jaylen      Brown   7.8  1.4  3.7

In [240]:
# sorting multiple values
multiple_sorted = sorted_celtics_df.sort_values(['ppg', 'rpg'], ascending = False)
multiple_sorted

  first_name  last_name   ppg  apg  rpg
1   Kristaps  Porzingis  27.4  8.3  8.5
4         Al    Horford  18.7  2.5  5.5
2     Jayson      Tatum  18.7  3.0  5.1
3    Derrick      White   9.9  5.4  5.3
0     Jaylen      Brown   7.8  1.4  3.7

# Filtering Data Frames

In [244]:
# reading in the 22-23 regular season stats, separated by semicolon
df = pd.read_csv('../stats-csv/player-stats-regular-season-22-23.csv', sep=';', encoding='latin1')

In [245]:
df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,...,0.702,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2
1,2,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,...,0.364,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
3,4,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,...,0.812,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9
4,5,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,...,0.750,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
674,535,Thaddeus Young,PF,34,TOR,54,9,14.7,2.0,3.7,...,0.692,1.3,1.8,3.1,1.4,1.0,0.1,0.8,1.6,4.4
675,536,Trae Young,PG,24,ATL,73,73,34.8,8.2,19.0,...,0.886,0.8,2.2,3.0,10.2,1.1,0.1,4.1,1.4,26.2
676,537,Omer Yurtseven,C,24,MIA,9,0,9.2,1.8,3.0,...,0.833,0.9,1.7,2.6,0.2,0.2,0.2,0.4,1.8,4.4
677,538,Cody Zeller,C,30,MIA,15,2,14.5,2.5,3.9,...,0.686,1.7,2.6,4.3,0.7,0.2,0.3,0.9,2.2,6.5
678,539,Ivica Zubac,C,25,LAC,76,76,28.6,4.3,6.8,...,0.697,3.1,6.8,9.9,1.0,0.4,1.3,1.5,2.9,10.8

In [247]:
# filter data frame to only show players who play for the Los Angeles Clippers
# evaluates each row to see if Tm value is LAC
df['Tm'] == 'LAC'

0      False
1      False
2      False
3      False
4      False
       ...
674    False
675    False
676    False
677    False
678     True
Name: Tm, Length: 679, dtype: bool

In [250]:
lac_df = df[df['Tm'] == 'LAC']
lac_df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
40,33,Nicolas Batum,PF,34,LAC,78,19,21.9,2.1,4.9,...,0.708,0.8,3.0,3.8,1.6,0.7,0.6,0.6,1.9,6.1
67,50,Brandon Boston Jr.,SG,21,LAC,22,1,11.3,2.3,5.5,...,0.763,0.3,1.0,1.4,0.9,0.4,0.0,0.5,1.0,6.5
88,66,Moses Brown,C,23,LAC,34,1,8.5,1.8,2.8,...,0.458,1.7,2.4,4.1,0.1,0.1,0.4,0.4,1.1,4.6
124,95,Amir Coffey,SG,25,LAC,50,9,12.5,1.1,2.9,...,0.778,0.3,0.7,1.1,1.1,0.1,0.1,0.4,1.0,3.4
133,102,Robert Covington,PF,32,LAC,48,0,16.2,2.1,4.8,...,0.750,0.6,2.8,3.5,1.2,0.8,0.7,0.7,1.8,6.0
151,118,Moussa Diabaté,PF,21,LAC,22,1,8.9,1.1,2.1,...,0.625,1.4,0.9,2.3,0.2,0.3,0.4,0.4,0.7,2.7
206,161,Paul George,SG,32,LAC,56,56,34.6,8.2,17.9,...,0.871,0.8,5.3,6.1,5.1,1.5,0.4,3.1,2.8,23.8
217,170,Eric Gordon,SG,34,LAC,22,11,24.9,3.7,8.0,...,0.842,0.2,1.5,1.7,2.1,0.6,0.4,1.0,1.5,11.0
288,225,Bones Hyland,PG,22,LAC,14,0,18.9,3.9,9.8,...,0.750,0.7,2.8,3.5,3.4,0.8,0.1,1.1,2.1,10.8
304,238,Reggie Jackson,PG,32,LAC,52,38,25.7,4.1,9.8,...,0.924,0.4,1.8,2.2,3.5,0.7,0.1,1.8,1.8,10.9
338,264,Luke Kennard,SG,26,LAC,35,11,20.7,2.8,6.0,...,0.950,0.2,2.2,2.4,1.1,0.5,0.1,0.9,1.3,7.8
369,288,Kawhi Leonard,SF,31,LAC,52,50,33.6,8.6,16.8,...,0.871,1.1,5.4,6.5,3.9,1.4,0.5,1.7,1.6,23.8
389,304,Terance Mann,SG,26,LAC,81,36,23.1,3.4,6.5,...,0.780,1.0,2.5,3.4,2.3,0.5,0.3,1.0,1.8,8.8
433,344,Xavier Moon,SG,28,LAC,4,0,5.0,0.8,2.3,...,0.000,0.0,0.8,0.8,1.3,0.0,0.0,0.3,0.5,1.8
436,347,Marcus Morris,PF,33,LAC,65,65,28.1,4.2,9.9,...,0.782,0.4,3.5,4.0,1.8,0.6,0.3,0.9,2.1,11.2
492,385,Mason Plumlee,C,32,LAC,23,4,19.9,2.8,3.8,...,0.772,1.8,5.1,6.9,1.7,0.5,0.5,1.3,2.4,7.5
505,396,Norman Powell,SG,29,LAC,60,8,26.1,5.7,11.8,...,0.812,0.4,2.5,2.9,1.8,0.8,0.3,1.7,2.1,17.0
506,397,Jason Preston,PG,23,LAC,14,0,8.9,1.3,2.9,...,0.000,0.1,1.4,1.6,1.9,0.1,0.0,0.7,0.5,2.9
630,497,John Wall,PG,32,LAC,34,3,22.2,4.1,9.9,...,0.681,0.4,2.3,2.7,5.2,0.8,0.4,2.4,1.7,11.4
644,507,Russell Westbrook,PG,34,LAC,21,21,30.2,6.1,12.5,...,0.658,1.4,3.4,4.9,7.6,1.1,0.5,3.4,2.0,15.8
678,539,Ivica Zubac,C,25,LAC,76,76,28.6,4.3,6.8,...,0.697,3.1,6.8,9.9,1.0,0.4,1.3,1.5,2.9,10.8

In [253]:
# or assign inner code as a variable, cleaner way of filtering
sac = (df['Tm'] == 'SAC')

In [254]:
df[sac]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
32,27,Harrison Barnes,PF,30,SAC,82,82,32.5,4.6,9.6,...,0.847,1.1,3.4,4.5,1.6,0.7,0.1,1.0,1.3,15.0
98,73,Deonte Burton,SG,29,SAC,2,0,3.0,0.0,1.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
143,112,Terence Davis,SG,25,SAC,64,5,13.1,2.4,5.7,...,0.791,0.3,1.9,2.2,1.0,0.7,0.2,0.8,1.6,6.7
149,116,Matthew Dellavedova,PG,32,SAC,32,0,6.7,0.5,1.6,...,0.571,0.0,0.4,0.4,1.3,0.2,0.0,0.3,0.6,1.5
166,131,PJ Dozier,SG,26,SAC,16,0,4.9,0.6,2.1,...,0.000,0.1,0.8,0.9,0.6,0.4,0.1,0.3,0.4,1.4
182,141,Kessler Edwards,SF,22,SAC,22,3,13.9,1.4,3.1,...,0.769,0.8,1.4,2.1,1.0,0.5,0.2,0.4,1.7,3.9
183,142,Keon Ellis,SG,23,SAC,16,0,4.4,0.4,1.0,...,0.571,0.3,0.3,0.5,0.4,0.3,0.1,0.1,0.6,1.5
198,153,De'Aaron Fox,PG,25,SAC,73,73,33.4,9.3,18.2,...,0.780,0.5,3.6,4.2,6.1,1.1,0.3,2.5,2.4,25.0
277,216,Richaun Holmes,C,29,SAC,42,1,8.3,1.3,2.1,...,0.789,0.7,1.2,1.9,0.2,0.1,0.3,0.3,1.2,3.1
283,222,Kevin Huerter,SG,24,SAC,75,75,29.4,5.6,11.5,...,0.725,0.6,2.8,3.3,2.9,1.1,0.3,1.3,2.4,15.2
368,287,Alex Len,C,29,SAC,26,2,6.2,0.6,1.2,...,0.688,0.9,1.4,2.3,0.5,0.2,0.4,0.6,1.1,1.7
384,301,Trey Lyles,PF,27,SAC,74,0,16.9,2.5,5.5,...,0.815,0.9,3.1,4.1,0.9,0.4,0.4,0.9,1.3,7.6
420,331,Chimezie Metu,C,25,SAC,66,0,10.4,2.0,3.3,...,0.740,0.7,2.3,3.0,0.6,0.3,0.3,0.5,1.2,4.9
426,337,Davion Mitchell,PG,24,SAC,80,9,18.1,2.3,5.0,...,0.806,0.2,1.1,1.3,2.3,0.6,0.2,0.8,1.4,5.6
430,341,Chima Moneke,SF,27,SAC,2,0,4.0,0.5,1.0,...,0.000,1.0,0.0,1.0,0.5,0.0,0.0,1.0,1.0,1.0
431,342,Malik Monk,SG,24,SAC,77,0,22.3,4.6,10.3,...,0.889,0.4,2.2,2.6,3.9,0.6,0.3,1.9,1.6,13.5
444,353,Keegan Murray,SF,22,SAC,80,78,29.8,4.4,9.8,...,0.765,1.1,3.5,4.6,1.2,0.8,0.5,0.8,2.0,12.2
475,374,KZ Okpala,PF,23,SAC,35,3,7.1,0.5,1.1,...,0.875,0.2,0.8,1.0,0.4,0.2,0.2,0.2,1.1,1.3
511,402,Neemias Queta,C,23,SAC,5,0,5.8,1.2,1.8,...,0.000,1.0,1.2,2.2,0.2,0.0,0.4,0.2,1.4,2.4
549,428,Domantas Sabonis,C,26,SAC,79,79,34.6,7.3,11.9,...,0.742,3.2,9.1,12.3,7.3,0.8,0.5,2.9,3.5,19.1

In [257]:
# filter players that play for Miami Heat or Portland Trailblazers
combined = df[(df['Tm'] == 'MIA') | (df['Tm'] == 'POR')]

In [258]:
combined

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
18,15,Ryan Arcidiacono,PG,28,POR,9,4,16.2,0.9,3.6,...,0.000,0.0,1.2,1.2,2.3,0.3,0.0,0.7,1.6,2.6
71,53,Jamaree Bouyea,PG,23,MIA,4,0,16.3,1.5,3.3,...,0.500,0.3,1.0,1.3,1.0,1.0,0.5,1.0,1.3,3.8
84,63,Greg Brown III,PF,21,POR,16,0,5.8,0.7,1.8,...,0.417,0.1,1.1,1.2,0.2,0.3,0.3,0.4,0.8,1.8
100,75,Jimmy Butler,SF,33,MIA,64,64,33.4,7.5,13.9,...,0.850,2.2,3.7,5.9,5.3,1.8,0.3,1.6,1.3,22.9
101,76,John Butler,C,20,POR,19,1,11.6,0.9,2.8,...,0.750,0.2,0.7,0.9,0.6,0.4,0.5,0.1,1.2,2.4
102,77,Jamal Cain,SF,23,MIA,18,0,13.3,2.1,3.7,...,0.773,0.8,2.1,2.9,0.7,0.6,0.1,0.3,1.2,5.4
127,98,Chance Comanche,C,26,POR,1,0,21.0,3.0,5.0,...,0.250,2.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,7.0
147,115,Dewayne Dedmon,C,33,MIA,30,0,11.7,2.1,4.3,...,0.727,0.9,2.7,3.6,0.5,0.2,0.5,0.6,2.0,5.7
185,144,Drew Eubanks,C,25,POR,78,28,20.3,2.7,4.3,...,0.664,1.7,3.7,5.4,1.3,0.5,1.3,0.9,2.2,6.6
221,172,Jerami Grant,PF,28,POR,63,63,35.7,6.9,14.5,...,0.813,0.8,3.7,4.5,2.4,0.8,0.8,1.8,2.4,20.5
253,198,Shaquille Harrison,SG,29,POR,5,0,24.0,3.0,7.2,...,0.733,0.2,4.2,4.4,6.0,2.2,0.4,1.2,2.4,8.8
255,199,Josh Hart,SF,27,POR,51,51,33.4,3.6,7.1,...,0.731,1.9,6.3,8.2,3.9,1.1,0.2,1.5,2.6,9.5
258,201,Udonis Haslem,C,42,MIA,7,1,10.1,1.4,4.1,...,0.800,0.6,1.0,1.6,0.0,0.1,0.3,0.1,1.6,3.9
265,208,Tyler Herro,SG,23,MIA,67,67,34.9,7.3,16.6,...,0.934,0.4,5.0,5.4,4.2,0.8,0.2,2.4,1.5,20.1
267,210,Haywood Highsmith,SF,26,MIA,54,11,17.9,1.7,4.0,...,0.464,1.1,2.4,3.5,0.8,0.7,0.3,0.8,1.5,4.4
316,247,Keon Johnson,SG,20,POR,40,0,10.4,1.7,4.5,...,0.659,0.3,0.8,1.1,1.5,0.5,0.2,1.1,1.1,4.7
330,259,Nikola Jovi?,PF,19,MIA,15,8,13.6,1.9,4.6,...,0.947,0.6,1.5,2.1,0.7,0.5,0.1,0.7,1.3,5.5
348,271,Kevin Knox,SF,23,POR,21,4,17.1,3.2,7.3,...,0.741,0.7,2.6,3.3,0.9,0.5,0.0,0.9,1.0,8.5
373,292,Damian Lillard,PG,32,POR,58,58,36.3,9.6,20.7,...,0.914,0.8,4.0,4.8,7.3,0.9,0.3,3.3,1.9,32.2
374,293,Nassir Little,SF,22,POR,54,4,18.1,2.5,5.6,...,0.717,0.5,2.1,2.6,0.9,0.4,0.4,0.7,1.2,6.6
382,299,Kevin Love,PF,34,MIA,21,17,20.0,2.6,6.6,...,0.857,0.8,4.9,5.7,1.9,0.4,0.2,1.1,1.5,7.7
383,300,Kyle Lowry,PG,36,MIA,55,44,31.2,3.6,8.8,...,0.859,0.8,3.3,4.1,5.1,1.0,0.4,1.9,2.6,11.2
394,309,Caleb Martin,PF,27,MIA,71,49,29.3,3.6,7.7,...,0.805,1.2,3.6,4.8,1.6,1.0,0.4,1.1,2.0,9.6
404,317,Skylar Mays,SG,25,POR,6,6,31.5,5.7,11.3,...,0.923,0.3,2.8,3.2,8.3,1.0,0.2,1.7,1.8,15.3
424,335,Justin Minaya,SF,23,POR,4,0,22.3,1.8,5.8,...,0.000,0.8,3.0,3.8,1.0,0.5,1.3,1.0,2.3,4.3
466,367,Jusuf Nurki?,C,28,POR,52,52,26.8,5.0,9.7,...,0.661,2.2,6.9,9.1,2.9,0.8,0.8,2.3,3.6,13.3
476,375,Victor Oladipo,SG,30,MIA,42,2,26.3,3.8,9.6,...,0.747,0.4,2.7,3.0,3.5,1.4,0.3,2.1,2.4,10.7
486,382,Gary Payton II,PG,30,POR,15,1,17.0,1.6,2.7,...,1.000,0.7,1.9,2.6,1.5,1.1,0.1,0.8,1.9,4.1
518,407,Cam Reddish,SF,23,POR,20,12,27.6,3.9,8.8,...,0.833,0.6,2.3,2.9,1.9,1.2,0.3,1.6,2.0,11.0
530,415,Duncan Robinson,SF,28,MIA,42,1,16.5,2.1,5.6,...,0.906,0.2,1.5,1.6,1.1,0.3,0.0,0.7,1.8,6.4
532,417,Orlando Robinson,C,22,MIA,31,1,13.7,1.5,2.9,...,0.710,1.5,2.5,4.1,0.8,0.4,0.4,0.5,1.7,3.7
564,441,Shaedon Sharpe,SG,19,POR,80,15,22.2,3.8,8.1,...,0.714,0.8,2.2,3.0,1.2,0.5,0.3,1.0,1.7,9.9
570,447,Anfernee Simons,SG,23,POR,62,62,35.0,7.5,16.9,...,0.894,0.3,2.3,2.6,4.1,0.7,0.2,2.1,2.3,21.1
575,451,Dru Smith,SG,25,MIA,5,1,13.4,1.0,2.8,...,0.000,0.2,1.6,1.8,1.0,0.8,0.6,0.2,2.0,2.2
585,460,Max Strus,SF,26,MIA,80,33,28.4,4.1,9.9,...,0.876,0.6,2.6,3.2,2.1,0.5,0.2,0.9,2.1,11.5
602,473,Matisse Thybulle,SG,25,POR,22,22,27.7,2.7,6.2,...,0.625,0.9,2.6,3.5,1.4,1.7,0.8,0.7,2.2,7.4
620,487,Gabe Vincent,PG,26,MIA,68,34,25.9,3.4,8.3,...,0.872,0.4,1.7,2.1,2.5,0.9,0.1,1.4,2.3,9.4
627,494,Jabari Walker,SF,20,POR,56,0,11.1,1.5,3.5,...,0.756,0.9,1.5,2.3,0.6,0.2,0.2,0.5,1.2,3.9
639,504,Trendon Watford,PF,22,POR,62,12,19.1,2.9,5.2,...,0.720,0.7,3.2,3.8,2.1,0.5,0.2,1.1,1.9,7.4
657,520,Jeenathan Williams,SG,23,POR,5,4,25.4,4.8,7.8,...,0.667,2.0,1.0,3.0,2.0,0.6,0.4,0.8,2.6,10.6
666,529,Justise Winslow,SF,26,POR,29,11,26.8,2.8,6.8,...,0.714,1.7,3.3,5.0,3.4,1.0,0.4,1.5,3.1,6.8
676,537,Omer Yurtseven,C,24,MIA,9,0,9.2,1.8,3.0,...,0.833,0.9,1.7,2.6,0.2,0.2,0.2,0.4,1.8,4.4
677,538,Cody Zeller,C,30,MIA,15,2,14.5,2.5,3.9,...,0.686,1.7,2.6,4.3,0.7,0.2,0.3,0.9,2.2,6.5

In [260]:
# cleaner way to do it
mia = (df['Tm'] == 'MIA')
por = (df['Tm'] == 'POR')
df[mia | por]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
18,15,Ryan Arcidiacono,PG,28,POR,9,4,16.2,0.9,3.6,...,0.000,0.0,1.2,1.2,2.3,0.3,0.0,0.7,1.6,2.6
71,53,Jamaree Bouyea,PG,23,MIA,4,0,16.3,1.5,3.3,...,0.500,0.3,1.0,1.3,1.0,1.0,0.5,1.0,1.3,3.8
84,63,Greg Brown III,PF,21,POR,16,0,5.8,0.7,1.8,...,0.417,0.1,1.1,1.2,0.2,0.3,0.3,0.4,0.8,1.8
100,75,Jimmy Butler,SF,33,MIA,64,64,33.4,7.5,13.9,...,0.850,2.2,3.7,5.9,5.3,1.8,0.3,1.6,1.3,22.9
101,76,John Butler,C,20,POR,19,1,11.6,0.9,2.8,...,0.750,0.2,0.7,0.9,0.6,0.4,0.5,0.1,1.2,2.4
102,77,Jamal Cain,SF,23,MIA,18,0,13.3,2.1,3.7,...,0.773,0.8,2.1,2.9,0.7,0.6,0.1,0.3,1.2,5.4
127,98,Chance Comanche,C,26,POR,1,0,21.0,3.0,5.0,...,0.250,2.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,7.0
147,115,Dewayne Dedmon,C,33,MIA,30,0,11.7,2.1,4.3,...,0.727,0.9,2.7,3.6,0.5,0.2,0.5,0.6,2.0,5.7
185,144,Drew Eubanks,C,25,POR,78,28,20.3,2.7,4.3,...,0.664,1.7,3.7,5.4,1.3,0.5,1.3,0.9,2.2,6.6
221,172,Jerami Grant,PF,28,POR,63,63,35.7,6.9,14.5,...,0.813,0.8,3.7,4.5,2.4,0.8,0.8,1.8,2.4,20.5
253,198,Shaquille Harrison,SG,29,POR,5,0,24.0,3.0,7.2,...,0.733,0.2,4.2,4.4,6.0,2.2,0.4,1.2,2.4,8.8
255,199,Josh Hart,SF,27,POR,51,51,33.4,3.6,7.1,...,0.731,1.9,6.3,8.2,3.9,1.1,0.2,1.5,2.6,9.5
258,201,Udonis Haslem,C,42,MIA,7,1,10.1,1.4,4.1,...,0.800,0.6,1.0,1.6,0.0,0.1,0.3,0.1,1.6,3.9
265,208,Tyler Herro,SG,23,MIA,67,67,34.9,7.3,16.6,...,0.934,0.4,5.0,5.4,4.2,0.8,0.2,2.4,1.5,20.1
267,210,Haywood Highsmith,SF,26,MIA,54,11,17.9,1.7,4.0,...,0.464,1.1,2.4,3.5,0.8,0.7,0.3,0.8,1.5,4.4
316,247,Keon Johnson,SG,20,POR,40,0,10.4,1.7,4.5,...,0.659,0.3,0.8,1.1,1.5,0.5,0.2,1.1,1.1,4.7
330,259,Nikola Jovi?,PF,19,MIA,15,8,13.6,1.9,4.6,...,0.947,0.6,1.5,2.1,0.7,0.5,0.1,0.7,1.3,5.5
348,271,Kevin Knox,SF,23,POR,21,4,17.1,3.2,7.3,...,0.741,0.7,2.6,3.3,0.9,0.5,0.0,0.9,1.0,8.5
373,292,Damian Lillard,PG,32,POR,58,58,36.3,9.6,20.7,...,0.914,0.8,4.0,4.8,7.3,0.9,0.3,3.3,1.9,32.2
374,293,Nassir Little,SF,22,POR,54,4,18.1,2.5,5.6,...,0.717,0.5,2.1,2.6,0.9,0.4,0.4,0.7,1.2,6.6
382,299,Kevin Love,PF,34,MIA,21,17,20.0,2.6,6.6,...,0.857,0.8,4.9,5.7,1.9,0.4,0.2,1.1,1.5,7.7
383,300,Kyle Lowry,PG,36,MIA,55,44,31.2,3.6,8.8,...,0.859,0.8,3.3,4.1,5.1,1.0,0.4,1.9,2.6,11.2
394,309,Caleb Martin,PF,27,MIA,71,49,29.3,3.6,7.7,...,0.805,1.2,3.6,4.8,1.6,1.0,0.4,1.1,2.0,9.6
404,317,Skylar Mays,SG,25,POR,6,6,31.5,5.7,11.3,...,0.923,0.3,2.8,3.2,8.3,1.0,0.2,1.7,1.8,15.3
424,335,Justin Minaya,SF,23,POR,4,0,22.3,1.8,5.8,...,0.000,0.8,3.0,3.8,1.0,0.5,1.3,1.0,2.3,4.3
466,367,Jusuf Nurki?,C,28,POR,52,52,26.8,5.0,9.7,...,0.661,2.2,6.9,9.1,2.9,0.8,0.8,2.3,3.6,13.3
476,375,Victor Oladipo,SG,30,MIA,42,2,26.3,3.8,9.6,...,0.747,0.4,2.7,3.0,3.5,1.4,0.3,2.1,2.4,10.7
486,382,Gary Payton II,PG,30,POR,15,1,17.0,1.6,2.7,...,1.000,0.7,1.9,2.6,1.5,1.1,0.1,0.8,1.9,4.1
518,407,Cam Reddish,SF,23,POR,20,12,27.6,3.9,8.8,...,0.833,0.6,2.3,2.9,1.9,1.2,0.3,1.6,2.0,11.0
530,415,Duncan Robinson,SF,28,MIA,42,1,16.5,2.1,5.6,...,0.906,0.2,1.5,1.6,1.1,0.3,0.0,0.7,1.8,6.4
532,417,Orlando Robinson,C,22,MIA,31,1,13.7,1.5,2.9,...,0.710,1.5,2.5,4.1,0.8,0.4,0.4,0.5,1.7,3.7
564,441,Shaedon Sharpe,SG,19,POR,80,15,22.2,3.8,8.1,...,0.714,0.8,2.2,3.0,1.2,0.5,0.3,1.0,1.7,9.9
570,447,Anfernee Simons,SG,23,POR,62,62,35.0,7.5,16.9,...,0.894,0.3,2.3,2.6,4.1,0.7,0.2,2.1,2.3,21.1
575,451,Dru Smith,SG,25,MIA,5,1,13.4,1.0,2.8,...,0.000,0.2,1.6,1.8,1.0,0.8,0.6,0.2,2.0,2.2
585,460,Max Strus,SF,26,MIA,80,33,28.4,4.1,9.9,...,0.876,0.6,2.6,3.2,2.1,0.5,0.2,0.9,2.1,11.5
602,473,Matisse Thybulle,SG,25,POR,22,22,27.7,2.7,6.2,...,0.625,0.9,2.6,3.5,1.4,1.7,0.8,0.7,2.2,7.4
620,487,Gabe Vincent,PG,26,MIA,68,34,25.9,3.4,8.3,...,0.872,0.4,1.7,2.1,2.5,0.9,0.1,1.4,2.3,9.4
627,494,Jabari Walker,SF,20,POR,56,0,11.1,1.5,3.5,...,0.756,0.9,1.5,2.3,0.6,0.2,0.2,0.5,1.2,3.9
639,504,Trendon Watford,PF,22,POR,62,12,19.1,2.9,5.2,...,0.720,0.7,3.2,3.8,2.1,0.5,0.2,1.1,1.9,7.4
657,520,Jeenathan Williams,SG,23,POR,5,4,25.4,4.8,7.8,...,0.667,2.0,1.0,3.0,2.0,0.6,0.4,0.8,2.6,10.6
666,529,Justise Winslow,SF,26,POR,29,11,26.8,2.8,6.8,...,0.714,1.7,3.3,5.0,3.4,1.0,0.4,1.5,3.1,6.8
676,537,Omer Yurtseven,C,24,MIA,9,0,9.2,1.8,3.0,...,0.833,0.9,1.7,2.6,0.2,0.2,0.2,0.4,1.8,4.4
677,538,Cody Zeller,C,30,MIA,15,2,14.5,2.5,3.9,...,0.686,1.7,2.6,4.3,0.7,0.2,0.3,0.9,2.2,6.5

In [263]:
# checking if both statements are true
# extracting all players who play for MIA and have played more than 50 games
df[(df['Tm'] == 'MIA') & (df['G'] > 50)]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
100,75,Jimmy Butler,SF,33,MIA,64,64,33.4,7.5,13.9,...,0.850,2.2,3.7,5.9,5.3,1.8,0.3,1.6,1.3,22.9
265,208,Tyler Herro,SG,23,MIA,67,67,34.9,7.3,16.6,...,0.934,0.4,5.0,5.4,4.2,0.8,0.2,2.4,1.5,20.1
267,210,Haywood Highsmith,SF,26,MIA,54,11,17.9,1.7,4.0,...,0.464,1.1,2.4,3.5,0.8,0.7,0.3,0.8,1.5,4.4
383,300,Kyle Lowry,PG,36,MIA,55,44,31.2,3.6,8.8,...,0.859,0.8,3.3,4.1,5.1,1.0,0.4,1.9,2.6,11.2
394,309,Caleb Martin,PF,27,MIA,71,49,29.3,3.6,7.7,...,0.805,1.2,3.6,4.8,1.6,1.0,0.4,1.1,2.0,9.6
585,460,Max Strus,SF,26,MIA,80,33,28.4,4.1,9.9,...,0.876,0.6,2.6,3.2,2.1,0.5,0.2,0.9,2.1,11.5
620,487,Gabe Vincent,PG,26,MIA,68,34,25.9,3.4,8.3,...,0.872,0.4,1.7,2.1,2.5,0.9,0.1,1.4,2.3,9.4

In [264]:
# or saving to two variables instead
gp = df['G'] > 50
df[mia & gp]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
100,75,Jimmy Butler,SF,33,MIA,64,64,33.4,7.5,13.9,...,0.850,2.2,3.7,5.9,5.3,1.8,0.3,1.6,1.3,22.9
265,208,Tyler Herro,SG,23,MIA,67,67,34.9,7.3,16.6,...,0.934,0.4,5.0,5.4,4.2,0.8,0.2,2.4,1.5,20.1
267,210,Haywood Highsmith,SF,26,MIA,54,11,17.9,1.7,4.0,...,0.464,1.1,2.4,3.5,0.8,0.7,0.3,0.8,1.5,4.4
383,300,Kyle Lowry,PG,36,MIA,55,44,31.2,3.6,8.8,...,0.859,0.8,3.3,4.1,5.1,1.0,0.4,1.9,2.6,11.2
394,309,Caleb Martin,PF,27,MIA,71,49,29.3,3.6,7.7,...,0.805,1.2,3.6,4.8,1.6,1.0,0.4,1.1,2.0,9.6
585,460,Max Strus,SF,26,MIA,80,33,28.4,4.1,9.9,...,0.876,0.6,2.6,3.2,2.1,0.5,0.2,0.9,2.1,11.5
620,487,Gabe Vincent,PG,26,MIA,68,34,25.9,3.4,8.3,...,0.872,0.4,1.7,2.1,2.5,0.9,0.1,1.4,2.3,9.4

In [271]:
# checking if any players were in the 50/40/90 club this season
fg = (df['FG%'] >= .50)
three_point = (df['3P%'] >= .40)
ft = (df['FT%'] >= .90)
elite_shooters = df[fg & three_point & ft]
elite_shooters[['Player', 'FG%', '3P%', 'FT%']]

               Player    FG%    3P%    FT%
73       Tony Bradley  0.500  0.600  1.000
75   Jarrell Brantley  0.571  0.444  1.000
174      Kevin Durant  0.560  0.404  0.919
222      RaiQuan Gray  0.500  0.400  1.000
226       Danny Green  0.500  0.448  1.000
284          Jay Huff  0.600  0.500  0.938
339      Luke Kennard  0.526  0.540  0.947
404       Skylar Mays  0.500  0.462  0.923
486    Gary Payton II  0.585  0.529  1.000
580      Xavier Sneed  0.500  0.500  1.000

In [272]:
df[(mia | por) & gp]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
100,75,Jimmy Butler,SF,33,MIA,64,64,33.4,7.5,13.9,...,0.850,2.2,3.7,5.9,5.3,1.8,0.3,1.6,1.3,22.9
185,144,Drew Eubanks,C,25,POR,78,28,20.3,2.7,4.3,...,0.664,1.7,3.7,5.4,1.3,0.5,1.3,0.9,2.2,6.6
221,172,Jerami Grant,PF,28,POR,63,63,35.7,6.9,14.5,...,0.813,0.8,3.7,4.5,2.4,0.8,0.8,1.8,2.4,20.5
255,199,Josh Hart,SF,27,POR,51,51,33.4,3.6,7.1,...,0.731,1.9,6.3,8.2,3.9,1.1,0.2,1.5,2.6,9.5
265,208,Tyler Herro,SG,23,MIA,67,67,34.9,7.3,16.6,...,0.934,0.4,5.0,5.4,4.2,0.8,0.2,2.4,1.5,20.1
267,210,Haywood Highsmith,SF,26,MIA,54,11,17.9,1.7,4.0,...,0.464,1.1,2.4,3.5,0.8,0.7,0.3,0.8,1.5,4.4
373,292,Damian Lillard,PG,32,POR,58,58,36.3,9.6,20.7,...,0.914,0.8,4.0,4.8,7.3,0.9,0.3,3.3,1.9,32.2
374,293,Nassir Little,SF,22,POR,54,4,18.1,2.5,5.6,...,0.717,0.5,2.1,2.6,0.9,0.4,0.4,0.7,1.2,6.6
383,300,Kyle Lowry,PG,36,MIA,55,44,31.2,3.6,8.8,...,0.859,0.8,3.3,4.1,5.1,1.0,0.4,1.9,2.6,11.2
394,309,Caleb Martin,PF,27,MIA,71,49,29.3,3.6,7.7,...,0.805,1.2,3.6,4.8,1.6,1.0,0.4,1.1,2.0,9.6
466,367,Jusuf Nurki?,C,28,POR,52,52,26.8,5.0,9.7,...,0.661,2.2,6.9,9.1,2.9,0.8,0.8,2.3,3.6,13.3
564,441,Shaedon Sharpe,SG,19,POR,80,15,22.2,3.8,8.1,...,0.714,0.8,2.2,3.0,1.2,0.5,0.3,1.0,1.7,9.9
570,447,Anfernee Simons,SG,23,POR,62,62,35.0,7.5,16.9,...,0.894,0.3,2.3,2.6,4.1,0.7,0.2,2.1,2.3,21.1
585,460,Max Strus,SF,26,MIA,80,33,28.4,4.1,9.9,...,0.876,0.6,2.6,3.2,2.1,0.5,0.2,0.9,2.1,11.5
620,487,Gabe Vincent,PG,26,MIA,68,34,25.9,3.4,8.3,...,0.872,0.4,1.7,2.1,2.5,0.9,0.1,1.4,2.3,9.4
627,494,Jabari Walker,SF,20,POR,56,0,11.1,1.5,3.5,...,0.756,0.9,1.5,2.3,0.6,0.2,0.2,0.5,1.2,3.9
639,504,Trendon Watford,PF,22,POR,62,12,19.1,2.9,5.2,...,0.720,0.7,3.2,3.8,2.1,0.5,0.2,1.1,1.9,7.4

In [278]:
# using the isin method, filter players who play for Boston, Chicago or LA
list = ['BOS', 'CHI', 'LAK']

In [279]:
df[df['Tm'].isin(list)]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
52,39,Patrick Beverley,PG,34,CHI,22,22,27.5,2.1,5.4,...,0.533,0.9,4.0,4.9,3.5,1.0,0.7,0.8,2.9,5.8
73,54,Tony Bradley,C,25,CHI,12,0,2.8,0.5,1.0,...,1.000,0.1,0.8,0.9,0.1,0.1,0.1,0.1,0.2,1.6
81,60,Malcolm Brogdon,PG,30,BOS,67,0,26.0,5.3,10.9,...,0.870,0.6,3.6,4.2,3.7,0.7,0.3,1.5,1.6,14.9
85,64,Jaylen Brown,SF,26,BOS,67,67,35.9,10.1,20.6,...,0.765,1.2,5.7,6.9,3.5,1.1,0.4,2.9,2.6,26.6
111,86,Alex Caruso,PG,28,CHI,67,36,23.5,1.9,4.3,...,0.808,0.6,2.3,2.9,2.9,1.5,0.7,1.1,2.4,5.6
117,88,Justin Champagnie,SF,21,BOS,2,0,11.5,1.0,6.0,...,0.000,1.0,1.0,2.0,1.5,0.5,0.0,0.0,0.5,2.5
144,113,JD Davison,PG,20,BOS,12,0,5.5,0.7,1.6,...,0.500,0.2,0.6,0.8,0.9,0.2,0.2,0.3,0.4,1.6
150,117,DeMar DeRozan,SF,33,CHI,74,74,36.2,8.9,17.6,...,0.872,0.5,4.2,4.6,5.1,1.1,0.5,2.1,2.5,24.5
163,128,Ayo Dosunmu,SG,23,CHI,80,51,26.2,3.5,7.1,...,0.805,0.6,2.2,2.8,2.6,0.8,0.3,1.2,2.3,8.6
168,132,Goran Dragi?,PG,36,CHI,51,0,15.4,2.5,5.9,...,0.659,0.3,1.1,1.4,2.7,0.2,0.1,1.1,1.2,6.4
170,133,Andre Drummond,C,29,CHI,67,0,12.7,2.5,4.1,...,0.536,2.1,4.6,6.6,0.5,0.7,0.4,1.1,1.7,6.0
230,179,Javonte Green,SG,29,CHI,32,1,15.0,1.9,3.4,...,0.667,0.8,1.9,2.8,0.7,0.8,0.7,0.6,1.6,5.2
234,183,Blake Griffin,C,33,BOS,41,16,13.9,1.5,3.2,...,0.656,1.1,2.6,3.8,1.5,0.3,0.2,0.5,1.8,4.1
259,202,Sam Hauser,PF,25,BOS,80,8,16.1,2.3,5.0,...,0.706,0.4,2.1,2.6,0.9,0.4,0.3,0.4,1.2,6.4
271,212,Malcolm Hill,SF,27,CHI,5,0,1.8,0.4,0.8,...,0.000,0.0,0.6,0.6,0.0,0.0,0.0,0.0,0.2,1.0
278,217,Al Horford,C,36,BOS,63,63,30.5,3.6,7.6,...,0.714,1.2,5.0,6.2,3.0,0.5,1.0,0.6,1.9,9.8
301,236,Justin Jackson,SF,27,BOS,23,0,4.7,0.3,1.2,...,0.500,0.1,0.7,0.7,0.4,0.2,0.2,0.1,0.3,0.9
319,250,Carlik Jones,PG,25,CHI,7,0,8.0,0.9,2.1,...,0.625,0.1,0.6,0.7,0.9,0.3,0.0,0.3,0.3,2.9
323,252,Derrick Jones Jr.,SF,25,CHI,64,0,14.0,1.8,3.6,...,0.738,0.9,1.5,2.4,0.5,0.5,0.6,0.4,1.3,5.0
332,261,Mfiondu Kabengele,PF,25,BOS,4,0,9.0,0.5,1.8,...,1.000,1.3,1.3,2.5,0.0,0.5,0.0,0.3,0.8,1.5
352,275,Luke Kornet,C,27,BOS,69,0,11.7,1.6,2.5,...,0.821,1.2,1.6,2.9,0.8,0.2,0.7,0.4,1.2,3.8
360,283,Zach LaVine,SG,27,CHI,77,77,35.9,8.7,18.0,...,0.848,0.5,3.9,4.5,4.2,0.9,0.2,2.5,2.1,24.8
447,354,Mike Muscala,C,31,BOS,20,4,16.2,2.1,4.5,...,0.692,0.7,2.7,3.4,0.6,0.2,0.3,0.5,1.4,5.9
509,400,Payton Pritchard,PG,25,BOS,48,3,13.4,2.1,5.1,...,0.750,0.5,1.3,1.8,1.3,0.3,0.0,0.8,0.8,5.6
569,446,Marko Simonovic,C,23,CHI,7,0,2.9,0.3,1.0,...,0.500,0.1,0.1,0.3,0.0,0.0,0.0,0.0,0.7,0.9
572,449,Marcus Smart,PG,28,BOS,61,61,32.1,4.1,9.9,...,0.746,0.8,2.4,3.1,6.3,1.5,0.4,2.3,2.8,11.5
590,465,Jayson Tatum,PF,24,BOS,74,74,36.9,9.8,21.1,...,0.854,1.1,7.7,8.8,4.6,1.1,0.7,2.9,2.2,30.1
593,466,Terry Taylor,PF,23,CHI,5,0,7.2,1.8,2.0,...,0.250,1.0,0.6,1.6,0.0,0.0,0.2,0.0,0.4,4.0
595,468,Dalen Terry,SG,20,CHI,38,0,5.6,0.8,1.9,...,0.667,0.3,0.7,1.0,0.6,0.3,0.1,0.2,0.6,2.2
621,488,Noah Vonleh,C,27,BOS,23,1,7.4,0.5,1.0,...,1.000,0.8,1.3,2.1,0.3,0.1,0.3,0.5,1.5,1.1
622,489,Nikola Vu?evi?,C,32,CHI,82,82,33.5,7.3,14.0,...,0.835,1.9,9.1,11.0,3.2,0.7,0.7,1.7,2.2,17.6
645,508,Coby White,SG,22,CHI,74,2,23.4,3.6,8.0,...,0.871,0.2,2.6,2.9,2.8,0.7,0.1,1.0,1.6,9.7
646,509,Derrick White,SG,28,BOS,82,70,28.3,4.3,9.2,...,0.875,0.6,2.9,3.6,3.9,0.7,0.9,1.2,2.2,12.4
654,517,Grant Williams,PF,24,BOS,79,23,25.9,2.7,6.0,...,0.770,1.1,3.5,4.6,1.7,0.5,0.4,1.0,2.4,8.1
660,523,Patrick Williams,PF,21,CHI,82,65,28.3,3.8,8.3,...,0.857,1.0,3.0,4.0,1.2,0.9,0.9,1.2,1.8,10.2
661,524,Robert Williams,C,25,BOS,35,20,23.5,3.6,4.9,...,0.610,3.0,5.4,8.3,1.4,0.6,1.4,1.0,1.9,8.0

# Groupby Method

In [282]:
type(df.groupby('Pos'))

pandas.core.groupby.generic.DataFrameGroupBy

In [284]:
# groupby team and sort by mean team age
grouped = df.groupby('Tm')

In [285]:
grouped['Age'].mean().sort_values(ascending=False)

Tm
MIL    29.523810
LAC    28.333333
DAL    28.086957
MIA    27.750000
PHO    27.600000
TOT    27.171429
CLE    27.111111
BRK    27.000000
CHI    26.777778
BOS    26.777778
DEN    26.722222
LAL    26.416667
GSW    26.333333
PHI    26.142857
TOR    25.900000
UTA    25.782609
SAC    25.750000
NOP    25.705882
WAS    25.652174
IND    25.500000
MIN    25.500000
NYK    25.000000
ATL    24.700000
CHO    24.578947
POR    24.500000
DET    24.272727
MEM    24.210526
ORL    23.900000
SAS    23.869565
HOU    23.666667
OKC    23.263158
Name: Age, dtype: float64

In [287]:
celtics = grouped.get_group('BOS')
celtics

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
81,60,Malcolm Brogdon,PG,30,BOS,67,0,26.0,5.3,10.9,...,0.870,0.6,3.6,4.2,3.7,0.7,0.3,1.5,1.6,14.9
85,64,Jaylen Brown,SF,26,BOS,67,67,35.9,10.1,20.6,...,0.765,1.2,5.7,6.9,3.5,1.1,0.4,2.9,2.6,26.6
117,88,Justin Champagnie,SF,21,BOS,2,0,11.5,1.0,6.0,...,0.000,1.0,1.0,2.0,1.5,0.5,0.0,0.0,0.5,2.5
144,113,JD Davison,PG,20,BOS,12,0,5.5,0.7,1.6,...,0.500,0.2,0.6,0.8,0.9,0.2,0.2,0.3,0.4,1.6
234,183,Blake Griffin,C,33,BOS,41,16,13.9,1.5,3.2,...,0.656,1.1,2.6,3.8,1.5,0.3,0.2,0.5,1.8,4.1
259,202,Sam Hauser,PF,25,BOS,80,8,16.1,2.3,5.0,...,0.706,0.4,2.1,2.6,0.9,0.4,0.3,0.4,1.2,6.4
278,217,Al Horford,C,36,BOS,63,63,30.5,3.6,7.6,...,0.714,1.2,5.0,6.2,3.0,0.5,1.0,0.6,1.9,9.8
301,236,Justin Jackson,SF,27,BOS,23,0,4.7,0.3,1.2,...,0.500,0.1,0.7,0.7,0.4,0.2,0.2,0.1,0.3,0.9
332,261,Mfiondu Kabengele,PF,25,BOS,4,0,9.0,0.5,1.8,...,1.000,1.3,1.3,2.5,0.0,0.5,0.0,0.3,0.8,1.5
352,275,Luke Kornet,C,27,BOS,69,0,11.7,1.6,2.5,...,0.821,1.2,1.6,2.9,0.8,0.2,0.7,0.4,1.2,3.8
447,354,Mike Muscala,C,31,BOS,20,4,16.2,2.1,4.5,...,0.692,0.7,2.7,3.4,0.6,0.2,0.3,0.5,1.4,5.9
509,400,Payton Pritchard,PG,25,BOS,48,3,13.4,2.1,5.1,...,0.750,0.5,1.3,1.8,1.3,0.3,0.0,0.8,0.8,5.6
572,449,Marcus Smart,PG,28,BOS,61,61,32.1,4.1,9.9,...,0.746,0.8,2.4,3.1,6.3,1.5,0.4,2.3,2.8,11.5
590,465,Jayson Tatum,PF,24,BOS,74,74,36.9,9.8,21.1,...,0.854,1.1,7.7,8.8,4.6,1.1,0.7,2.9,2.2,30.1
621,488,Noah Vonleh,C,27,BOS,23,1,7.4,0.5,1.0,...,1.000,0.8,1.3,2.1,0.3,0.1,0.3,0.5,1.5,1.1
646,509,Derrick White,SG,28,BOS,82,70,28.3,4.3,9.2,...,0.875,0.6,2.9,3.6,3.9,0.7,0.9,1.2,2.2,12.4
654,517,Grant Williams,PF,24,BOS,79,23,25.9,2.7,6.0,...,0.770,1.1,3.5,4.6,1.7,0.5,0.4,1.0,2.4,8.1
661,524,Robert Williams,C,25,BOS,35,20,23.5,3.6,4.9,...,0.610,3.0,5.4,8.3,1.4,0.6,1.4,1.0,1.9,8.0

In [288]:
positions = df.groupby('Pos')

In [292]:
list = ['PTS','TRB']
positions[list].sum()

          PTS    TRB
Pos
C      1024.8  673.5
PF     1034.3  488.6
PF-SF    43.2   12.4
PG     1341.3  362.6
SF     1103.6  391.6
SF-SG     9.8    7.8
SG     1451.0  412.2
SG-PG     7.1    1.6

In [293]:
positions['TRB'].describe()

       count      mean       std  min   25%  50%    75%   max
Pos
C      129.0  5.220930  3.009793  0.0  3.00  4.3  7.300  12.5
PF     117.0  4.176068  2.254637  0.0  2.50  3.9  5.400  11.8
PF-SF    3.0  4.133333  2.223361  2.8  2.85  2.9  4.800   6.7
PG     135.0  2.685926  1.624815  0.0  1.40  2.4  3.650   8.6
SF     125.0  3.132800  1.689091  0.0  2.00  3.1  4.200   8.6
SF-SG    1.0  7.800000       NaN  7.8  7.80  7.8  7.800   7.8
SG     168.0  2.453571  1.370908  0.0  1.40  2.2  3.225   7.9
SG-PG    1.0  1.600000       NaN  1.6  1.60  1.6  1.600   1.6

In [ ]:
# aggregation method

In [295]:
positions.agg({
    'PTS': 'sum',
    'TRB': 'mean'
})

          PTS       TRB
Pos
C      1024.8  5.220930
PF     1034.3  4.176068
PF-SF    43.2  4.133333
PG     1341.3  2.685926
SF     1103.6  3.132800
SF-SG     9.8  7.800000
SG     1451.0  2.453571
SG-PG     7.1  1.600000

# Concatenate and Append Datasets

In [296]:
df_1 = df.sample(5)
df_2 = df.sample(5)

In [297]:
df_1

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
555,432,Jordan Schakel,SF,24,WAS,2,0,3.0,0.5,1.0,...,0.000,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.5,1.5
164,129,Devon Dotson,PG,23,WAS,6,0,8.8,0.2,1.7,...,0.000,1.0,0.7,1.7,1.3,0.8,0.0,0.5,1.5,0.5
95,70,Thomas Bryant,C,25,DEN,18,1,11.4,1.8,3.8,...,0.722,1.1,2.3,3.3,0.1,0.1,0.4,0.6,1.4,4.6
205,160,Rudy Gay,PF,36,UTA,56,0,14.6,1.9,5.1,...,0.857,0.6,2.3,2.9,1.0,0.3,0.3,0.7,1.2,5.2
32,27,Harrison Barnes,PF,30,SAC,82,82,32.5,4.6,9.6,...,0.847,1.1,3.4,4.5,1.6,0.7,0.1,1.0,1.3,15.0

In [298]:
df_2

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
507,398,Joshua Primo,SG,20,SAS,4,0,23.3,2.3,6.5,...,0.778,0.5,2.8,3.3,4.5,0.3,0.5,2.8,2.0,7.0
540,423,Terrence Ross,SG,31,PHO,21,0,18.4,3.4,7.9,...,0.857,0.6,2.7,3.3,2.0,0.5,0.1,0.3,2.1,9.0
558,435,Jay Scrubb,SG,22,ORL,2,0,15.0,2.5,3.5,...,0.500,0.0,3.0,3.0,0.5,1.0,0.0,1.5,1.0,6.5
475,374,KZ Okpala,PF,23,SAC,35,3,7.1,0.5,1.1,...,0.875,0.2,0.8,1.0,0.4,0.2,0.2,0.2,1.1,1.3
235,184,Quentin Grimes,SG,22,NYK,71,66,29.9,4.0,8.5,...,0.796,0.7,2.5,3.2,2.1,0.7,0.4,1.0,2.5,11.3

In [300]:
df_new = pd.concat([df_1, df_2])

In [301]:
df_new

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
555,432,Jordan Schakel,SF,24,WAS,2,0,3.0,0.5,1.0,...,0.000,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.5,1.5
164,129,Devon Dotson,PG,23,WAS,6,0,8.8,0.2,1.7,...,0.000,1.0,0.7,1.7,1.3,0.8,0.0,0.5,1.5,0.5
95,70,Thomas Bryant,C,25,DEN,18,1,11.4,1.8,3.8,...,0.722,1.1,2.3,3.3,0.1,0.1,0.4,0.6,1.4,4.6
205,160,Rudy Gay,PF,36,UTA,56,0,14.6,1.9,5.1,...,0.857,0.6,2.3,2.9,1.0,0.3,0.3,0.7,1.2,5.2
32,27,Harrison Barnes,PF,30,SAC,82,82,32.5,4.6,9.6,...,0.847,1.1,3.4,4.5,1.6,0.7,0.1,1.0,1.3,15.0
507,398,Joshua Primo,SG,20,SAS,4,0,23.3,2.3,6.5,...,0.778,0.5,2.8,3.3,4.5,0.3,0.5,2.8,2.0,7.0
540,423,Terrence Ross,SG,31,PHO,21,0,18.4,3.4,7.9,...,0.857,0.6,2.7,3.3,2.0,0.5,0.1,0.3,2.1,9.0
558,435,Jay Scrubb,SG,22,ORL,2,0,15.0,2.5,3.5,...,0.500,0.0,3.0,3.0,0.5,1.0,0.0,1.5,1.0,6.5
475,374,KZ Okpala,PF,23,SAC,35,3,7.1,0.5,1.1,...,0.875,0.2,0.8,1.0,0.4,0.2,0.2,0.2,1.1,1.3
235,184,Quentin Grimes,SG,22,NYK,71,66,29.9,4.0,8.5,...,0.796,0.7,2.5,3.2,2.1,0.7,0.4,1.0,2.5,11.3

In [303]:
# reset the indexes for each row
df_new.reset_index(drop=True)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,432,Jordan Schakel,SF,24,WAS,2,0,3.0,0.5,1.0,...,0.000,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.5,1.5
1,129,Devon Dotson,PG,23,WAS,6,0,8.8,0.2,1.7,...,0.000,1.0,0.7,1.7,1.3,0.8,0.0,0.5,1.5,0.5
2,70,Thomas Bryant,C,25,DEN,18,1,11.4,1.8,3.8,...,0.722,1.1,2.3,3.3,0.1,0.1,0.4,0.6,1.4,4.6
3,160,Rudy Gay,PF,36,UTA,56,0,14.6,1.9,5.1,...,0.857,0.6,2.3,2.9,1.0,0.3,0.3,0.7,1.2,5.2
4,27,Harrison Barnes,PF,30,SAC,82,82,32.5,4.6,9.6,...,0.847,1.1,3.4,4.5,1.6,0.7,0.1,1.0,1.3,15.0
5,398,Joshua Primo,SG,20,SAS,4,0,23.3,2.3,6.5,...,0.778,0.5,2.8,3.3,4.5,0.3,0.5,2.8,2.0,7.0
6,423,Terrence Ross,SG,31,PHO,21,0,18.4,3.4,7.9,...,0.857,0.6,2.7,3.3,2.0,0.5,0.1,0.3,2.1,9.0
7,435,Jay Scrubb,SG,22,ORL,2,0,15.0,2.5,3.5,...,0.500,0.0,3.0,3.0,0.5,1.0,0.0,1.5,1.0,6.5
8,374,KZ Okpala,PF,23,SAC,35,3,7.1,0.5,1.1,...,0.875,0.2,0.8,1.0,0.4,0.2,0.2,0.2,1.1,1.3
9,184,Quentin Grimes,SG,22,NYK,71,66,29.9,4.0,8.5,...,0.796,0.7,2.5,3.2,2.1,0.7,0.4,1.0,2.5,11.3

In [305]:
# or using this one-liner
df_new = pd.concat([df_1, df_2], ignore_index=True)
df_new

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,432,Jordan Schakel,SF,24,WAS,2,0,3.0,0.5,1.0,...,0.000,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.5,1.5
1,129,Devon Dotson,PG,23,WAS,6,0,8.8,0.2,1.7,...,0.000,1.0,0.7,1.7,1.3,0.8,0.0,0.5,1.5,0.5
2,70,Thomas Bryant,C,25,DEN,18,1,11.4,1.8,3.8,...,0.722,1.1,2.3,3.3,0.1,0.1,0.4,0.6,1.4,4.6
3,160,Rudy Gay,PF,36,UTA,56,0,14.6,1.9,5.1,...,0.857,0.6,2.3,2.9,1.0,0.3,0.3,0.7,1.2,5.2
4,27,Harrison Barnes,PF,30,SAC,82,82,32.5,4.6,9.6,...,0.847,1.1,3.4,4.5,1.6,0.7,0.1,1.0,1.3,15.0
5,398,Joshua Primo,SG,20,SAS,4,0,23.3,2.3,6.5,...,0.778,0.5,2.8,3.3,4.5,0.3,0.5,2.8,2.0,7.0
6,423,Terrence Ross,SG,31,PHO,21,0,18.4,3.4,7.9,...,0.857,0.6,2.7,3.3,2.0,0.5,0.1,0.3,2.1,9.0
7,435,Jay Scrubb,SG,22,ORL,2,0,15.0,2.5,3.5,...,0.500,0.0,3.0,3.0,0.5,1.0,0.0,1.5,1.0,6.5
8,374,KZ Okpala,PF,23,SAC,35,3,7.1,0.5,1.1,...,0.875,0.2,0.8,1.0,0.4,0.2,0.2,0.2,1.1,1.3
9,184,Quentin Grimes,SG,22,NYK,71,66,29.9,4.0,8.5,...,0.796,0.7,2.5,3.2,2.1,0.7,0.4,1.0,2.5,11.3

In [307]:
# append runs on the dataframe itself
df_appended = df_2.append(df_1)
df_appended.reset_index(drop=True)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,398,Joshua Primo,SG,20,SAS,4,0,23.3,2.3,6.5,...,0.778,0.5,2.8,3.3,4.5,0.3,0.5,2.8,2.0,7.0
1,423,Terrence Ross,SG,31,PHO,21,0,18.4,3.4,7.9,...,0.857,0.6,2.7,3.3,2.0,0.5,0.1,0.3,2.1,9.0
2,435,Jay Scrubb,SG,22,ORL,2,0,15.0,2.5,3.5,...,0.500,0.0,3.0,3.0,0.5,1.0,0.0,1.5,1.0,6.5
3,374,KZ Okpala,PF,23,SAC,35,3,7.1,0.5,1.1,...,0.875,0.2,0.8,1.0,0.4,0.2,0.2,0.2,1.1,1.3
4,184,Quentin Grimes,SG,22,NYK,71,66,29.9,4.0,8.5,...,0.796,0.7,2.5,3.2,2.1,0.7,0.4,1.0,2.5,11.3
5,432,Jordan Schakel,SF,24,WAS,2,0,3.0,0.5,1.0,...,0.000,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.5,1.5
6,129,Devon Dotson,PG,23,WAS,6,0,8.8,0.2,1.7,...,0.000,1.0,0.7,1.7,1.3,0.8,0.0,0.5,1.5,0.5
7,70,Thomas Bryant,C,25,DEN,18,1,11.4,1.8,3.8,...,0.722,1.1,2.3,3.3,0.1,0.1,0.4,0.6,1.4,4.6
8,160,Rudy Gay,PF,36,UTA,56,0,14.6,1.9,5.1,...,0.857,0.6,2.3,2.9,1.0,0.3,0.3,0.7,1.2,5.2
9,27,Harrison Barnes,PF,30,SAC,82,82,32.5,4.6,9.6,...,0.847,1.1,3.4,4.5,1.6,0.7,0.1,1.0,1.3,15.0

# Merging and Joining Dataframes

In [308]:
df_A = pd.read_csv('../stats-csv/player_general_traditional_per_game_data.csv')
df_B = pd.read_csv('../stats-csv/player_id_player_name.csv')

In [309]:
df_A.head(5)

,player_id,season_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,...,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
0,471,1996-97,41.0,NaN,13.3,1.1,3.3,0.331,0.2,0.7,...,1.0,1.2,0.875,0.7,1.8,1.4,0.8,0.2,0.3,3.4
1,920,1996-97,83.0,33.0,30.8,2.8,5.8,0.483,0.0,0.2,...,1.5,2.4,0.650,2.7,5.2,0.8,0.9,0.8,0.2,7.2
2,243,1996-97,83.0,24.0,20.4,1.8,4.4,0.411,0.5,1.2,...,1.1,1.3,0.836,0.5,2.2,1.9,1.1,0.9,0.3,5.2
3,1425,1996-97,33.0,25.0,17.8,2.6,4.5,0.574,0.0,0.0,...,1.0,1.5,0.673,1.9,2.5,0.5,1.0,0.5,0.9,6.2
4,768,1996-97,47.0,27.0,11.1,1.4,3.8,0.374,0.0,0.1,...,1.1,1.8,0.643,0.7,1.3,0.4,0.7,0.3,0.6,4.0

In [310]:
df_B.head(5)

   player_id     player_name
0    1627773      AJ Hammons
1     201166    Aaron Brooks
2     203932    Aaron Gordon
3    1626151  Aaron Harrison
4     203940   Adreian Payne

In [311]:
# using the player_id column, merge the dataframes
merged = pd.merge(df_A, df_B, on='player_id')

In [312]:
merged.sample(5)

,player_id,season_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,...,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts,player_name
1870,201936,2018-19,69.0,29.0,20.3,3.7,9.6,0.389,1.1,3.1,...,2.3,0.719,0.5,2.4,2.4,1.7,0.8,0.3,10.2,Tyreke Evans
1442,201599,2015-16,77.0,27.0,33.7,4.6,6.6,0.703,0.0,0.0,...,8.0,0.430,3.5,10.3,1.2,1.4,0.7,2.3,12.7,DeAndre Jordan
810,101123,2014-15,74.0,29.0,19.5,4.4,10.5,0.416,1.9,5.2,...,1.6,0.825,0.4,2.1,1.2,1.4,0.6,0.2,11.9,Gerald Green
522,2738,2018-19,68.0,35.0,23.2,2.2,4.4,0.500,0.7,2.1,...,1.0,0.582,0.7,3.0,3.2,0.8,0.9,0.8,5.7,Andre Iguodala
885,101145,2012-13,82.0,27.0,37.5,7.3,17.5,0.416,1.1,4.0,...,4.6,0.773,0.5,3.3,6.0,3.1,2.1,0.4,19.2,Monta Ellis

In [316]:
# specify certain columns into the merge
merged = pd.merge(df_B, df_A[['player_id', 'season_id','pts']], on='player_id', how='inner')
merged.sample(5)

      player_id        player_name season_id   pts
2104       2449         Luis Scola   2013-14   7.6
337      203078       Bradley Beal   2012-13  13.9
2772       2210  Richard Jefferson   2004-05  22.2
3163     201962      Toney Douglas   2015-16   8.7
995      202683        Enes Kanter   2013-14  12.3

In [317]:
# if the column names you want to match are named differently, use the left_on and right_on parameters

In [329]:
raw_data = {
        'id': ['1', '2', '3', '4', '5', '6', '7'],
        'first_name': ['Jayson', 'Lebron', 'Kevin', 'Stephen', 'Nikola', 'Chris', 'Joel'], 
        'last_name': ['Tatum', 'James', 'Durant', 'Curry', 'Jokic', 'Paul', 'Embiid']}

In [330]:
df_1 = pd.DataFrame(raw_data, columns = ['id', 'first_name', 'last_name'])
df_1

  id first_name last_name
0  1     Jayson     Tatum
1  2     Lebron     James
2  3      Kevin    Durant
3  4    Stephen     Curry
4  5     Nikola     Jokic
5  6      Chris      Paul
6  7       Joel    Embiid

In [331]:
raw_data = {
        'player_id': ['1', '2', '3', '4', '5'],
        'career_ppg': [24.2, 25.7, 26.2, 25.9, 24.8]}

In [332]:
df_2 = pd.DataFrame(raw_data, columns = ['player_id','career_ppg'])
df_2

  player_id  career_ppg
0         1        24.2
1         2        25.7
2         3        26.2
3         4        25.9
4         5        24.8

In [334]:
df_3 = pd.merge(df_1, df_2, how = 'right', left_on = 'id', right_on = 'player_id')
df_3

  id first_name last_name player_id  career_ppg
0  1     Jayson     Tatum         1        24.2
1  2     Lebron     James         2        25.7
2  3      Kevin    Durant         3        26.2
3  4    Stephen     Curry         4        25.9
4  5     Nikola     Jokic         5        24.8

In [335]:
# drop the duplicate id column
df_4 = pd.merge(df_1, df_2, how = 'right', left_on = 'id', right_on = 'player_id').drop('id', axis = 1)
df_4

  first_name last_name player_id  career_ppg
0     Jayson     Tatum         1        24.2
1     Lebron     James         2        25.7
2      Kevin    Durant         3        26.2
3    Stephen     Curry         4        25.9
4     Nikola     Jokic         5        24.8

# Iterating over Dataframes

In [336]:
celtics

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
81,60,Malcolm Brogdon,PG,30,BOS,67,0,26.0,5.3,10.9,...,0.870,0.6,3.6,4.2,3.7,0.7,0.3,1.5,1.6,14.9
85,64,Jaylen Brown,SF,26,BOS,67,67,35.9,10.1,20.6,...,0.765,1.2,5.7,6.9,3.5,1.1,0.4,2.9,2.6,26.6
117,88,Justin Champagnie,SF,21,BOS,2,0,11.5,1.0,6.0,...,0.000,1.0,1.0,2.0,1.5,0.5,0.0,0.0,0.5,2.5
144,113,JD Davison,PG,20,BOS,12,0,5.5,0.7,1.6,...,0.500,0.2,0.6,0.8,0.9,0.2,0.2,0.3,0.4,1.6
234,183,Blake Griffin,C,33,BOS,41,16,13.9,1.5,3.2,...,0.656,1.1,2.6,3.8,1.5,0.3,0.2,0.5,1.8,4.1
259,202,Sam Hauser,PF,25,BOS,80,8,16.1,2.3,5.0,...,0.706,0.4,2.1,2.6,0.9,0.4,0.3,0.4,1.2,6.4
278,217,Al Horford,C,36,BOS,63,63,30.5,3.6,7.6,...,0.714,1.2,5.0,6.2,3.0,0.5,1.0,0.6,1.9,9.8
301,236,Justin Jackson,SF,27,BOS,23,0,4.7,0.3,1.2,...,0.500,0.1,0.7,0.7,0.4,0.2,0.2,0.1,0.3,0.9
332,261,Mfiondu Kabengele,PF,25,BOS,4,0,9.0,0.5,1.8,...,1.000,1.3,1.3,2.5,0.0,0.5,0.0,0.3,0.8,1.5
352,275,Luke Kornet,C,27,BOS,69,0,11.7,1.6,2.5,...,0.821,1.2,1.6,2.9,0.8,0.2,0.7,0.4,1.2,3.8
447,354,Mike Muscala,C,31,BOS,20,4,16.2,2.1,4.5,...,0.692,0.7,2.7,3.4,0.6,0.2,0.3,0.5,1.4,5.9
509,400,Payton Pritchard,PG,25,BOS,48,3,13.4,2.1,5.1,...,0.750,0.5,1.3,1.8,1.3,0.3,0.0,0.8,0.8,5.6
572,449,Marcus Smart,PG,28,BOS,61,61,32.1,4.1,9.9,...,0.746,0.8,2.4,3.1,6.3,1.5,0.4,2.3,2.8,11.5
590,465,Jayson Tatum,PF,24,BOS,74,74,36.9,9.8,21.1,...,0.854,1.1,7.7,8.8,4.6,1.1,0.7,2.9,2.2,30.1
621,488,Noah Vonleh,C,27,BOS,23,1,7.4,0.5,1.0,...,1.000,0.8,1.3,2.1,0.3,0.1,0.3,0.5,1.5,1.1
646,509,Derrick White,SG,28,BOS,82,70,28.3,4.3,9.2,...,0.875,0.6,2.9,3.6,3.9,0.7,0.9,1.2,2.2,12.4
654,517,Grant Williams,PF,24,BOS,79,23,25.9,2.7,6.0,...,0.770,1.1,3.5,4.6,1.7,0.5,0.4,1.0,2.4,8.1
661,524,Robert Williams,C,25,BOS,35,20,23.5,3.6,4.9,...,0.610,3.0,5.4,8.3,1.4,0.6,1.4,1.0,1.9,8.0

In [337]:
for row in celtics.iterrows():
    print(row)

(81, Rk                     60
Player    Malcolm Brogdon
Pos                    PG
Age                    30
Tm                    BOS
G                      67
GS                      0
MP                     26
FG                    5.3
FGA                  10.9
FG%                 0.484
3P                      2
3PA                   4.4
3P%                 0.444
2P                    3.3
2PA                   6.5
2P%                  0.51
eFG%                0.574
FT                    2.4
FTA                   2.7
FT%                  0.87
ORB                   0.6
DRB                   3.6
TRB                   4.2
AST                   3.7
STL                   0.7
BLK                   0.3
TOV                   1.5
PF                    1.6
PTS                  14.9
Name: 81, dtype: object)
(85, Rk                  64
Player    Jaylen Brown
Pos                 SF
Age                 26
Tm                 BOS
G                   67
GS                  67
MP                35.9
FG                10.1
FGA               20.6
FG%              0.491
3P                 2.4
3PA                7.3
3P%              0.335
2P                 7.7
2PA               13.4
2P%              0.576
eFG%              0.55
FT                 3.9
FTA                5.1
FT%              0.765
ORB                1.2
DRB                5.7
TRB                6.9
AST                3.5
STL                1.1
BLK                0.4
TOV                2.9
PF                 2.6
PTS               26.6
Name: 85, dtype: object)
(117, Rk                       88
Player    Justin Champagnie
Pos                      SF
Age                      21
Tm                      BOS
G                         2
GS                        0
MP                     11.5
FG                        1
FGA                       6
FG%                   0.167
3P                      0.5
3PA                     2.5
3P%                     0.2
2P                      0.5
2PA                     3.5
2P%                   0.143
eFG%                  0.208
FT                        0
FTA                       0
FT%                       0
ORB                       1
DRB                       1
TRB                       2
AST                     1.5
STL                     0.5
BLK                       0
TOV                       0
PF                      0.5
PTS                     2.5
Name: 117, dtype: object)
(144, Rk               113
Player    JD Davison
Pos               PG
Age               20
Tm               BOS
G                 12
GS                 0
MP               5.5
FG               0.7
FGA              1.6
FG%            0.421
3P               0.2
3PA              0.6
3P%            0.286
2P               0.5
2PA                1
2P%              0.5
eFG%           0.474
FT               0.1
FTA              0.2
FT%              0.5
ORB              0.2
DRB              0.6
TRB              0.8
AST              0.9
STL              0.2
BLK              0.2
TOV              0.3
PF               0.4
PTS              1.6
Name: 144, dtype: object)
(234, Rk                  183
Player    Blake Griffin
Pos                   C
Age                  33
Tm                  BOS
G                    41
GS                   16
MP                 13.9
FG                  1.5
FGA                 3.2
FG%               0.485
3P                  0.6
3PA                 1.6
3P%               0.348
2P                    1
2PA                 1.6
2P%               0.625
eFG%              0.573
FT                  0.5
FTA                 0.8
FT%               0.656
ORB                 1.1
DRB                 2.6
TRB                 3.8
AST                 1.5
STL                 0.3
BLK                 0.2
TOV                 0.5
PF                  1.8
PTS                 4.1
Name: 234, dtype: object)
(259, Rk               202
Player    Sam Hauser
Pos               PF
Age               25
Tm               BOS
G                 80
GS                 8
MP              16.1
FG               2.3
FGA                5
FG%            0.455
3P               1.8
3PA              4.2
3P%            0.418
2P               0.5
2PA              0.8
2P%            0.656
eFG%           0.631
FT               0.2
FTA              0.2
FT%            0.706
ORB              0.4
DRB              2.1
TRB              2.6
AST              0.9
STL              0.4
BLK              0.3
TOV              0.4
PF               1.2
PTS              6.4
Name: 259, dtype: object)
(278, Rk               217
Player    Al Horford
Pos                C
Age               36
Tm               BOS
G                 63
GS                63
MP              30.5
FG               3.6
FGA              7.6
FG%            0.476
3P               2.3
3PA              5.2
3P%            0.446
2P               1.3
2PA              2.4
2P%            0.539
eFG%           0.627
FT               0.2
FTA              0.3
FT%            0.714
ORB              1.2
DRB                5
TRB              6.2
AST                3
STL              0.5
BLK                1
TOV              0.6
PF               1.9
PTS              9.8
Name: 278, dtype: object)
(301, Rk                   236
Player    Justin Jackson
Pos                   SF
Age                   27
Tm                   BOS
G                     23
GS                     0
MP                   4.7
FG                   0.3
FGA                  1.2
FG%                0.259
3P                   0.2
3PA                  0.9
3P%                 0.25
2P                   0.1
2PA                  0.3
2P%                0.286
eFG%               0.352
FT                     0
FTA                  0.1
FT%                  0.5
ORB                  0.1
DRB                  0.7
TRB                  0.7
AST                  0.4
STL                  0.2
BLK                  0.2
TOV                  0.1
PF                   0.3
PTS                  0.9
Name: 301, dtype: object)
(332, Rk                      261
Player    Mfiondu Kabengele
Pos                      PF
Age                      25
Tm                      BOS
G                         4
GS                        0
MP                        9
FG                      0.5
FGA                     1.8
FG%                   0.286
3P                        0
3PA                     0.8
3P%                       0
2P                      0.5
2PA                       1
2P%                     0.5
eFG%                  0.286
FT                      0.5
FTA                     0.5
FT%                       1
ORB                     1.3
DRB                     1.3
TRB                     2.5
AST                       0
STL                     0.5
BLK                       0
TOV                     0.3
PF                      0.8
PTS                     1.5
Name: 332, dtype: object)
(352, Rk                275
Player    Luke Kornet
Pos                 C
Age                27
Tm                BOS
G                  69
GS                  0
MP               11.7
FG                1.6
FGA               2.5
FG%             0.665
3P                  0
3PA               0.2
3P%             0.231
2P                1.6
2PA               2.3
2P%             0.701
eFG%            0.674
FT                0.5
FTA               0.6
FT%             0.821
ORB               1.2
DRB               1.6
TRB               2.9
AST               0.8
STL               0.2
BLK               0.7
TOV               0.4
PF                1.2
PTS               3.8
Name: 352, dtype: object)
(447, Rk                 354
Player    Mike Muscala
Pos                  C
Age                 31
Tm                 BOS
G                   20
GS                   4
MP                16.2
FG                 2.1
FGA                4.5
FG%              0.472
3P                 1.3
3PA                3.3
3P%              0.385
2P                 0.9
2PA                1.2
2P%              0.708
eFG%             0.612
FT                 0.5
FTA                0.7
FT%              0.692
ORB                0.7
DRB                2.7
TRB                3.4
AST                0.6
STL                0.2
BLK                0.3
TOV                0.5
PF                 1.4
PTS                5.9
Name: 447, dtype: object)
(509, Rk                     400
Player    Payton Pritchard
Pos                     PG
Age                     25
Tm                     BOS
G                       48
GS                       3
MP                    13.4
FG                     2.1
FGA                    5.1
FG%                  0.412
3P                     1.2
3PA                    3.2
3P%                  0.364
2P                     0.9
2PA                    1.9
2P%                  0.495
eFG%                 0.527
FT                     0.3
FTA                    0.3
FT%                   0.75
ORB                    0.5
DRB                    1.3
TRB                    1.8
AST                    1.3
STL                    0.3
BLK                      0
TOV                    0.8
PF                     0.8
PTS                    5.6
Name: 509, dtype: object)
(572, Rk                 449
Player    Marcus Smart
Pos                 PG
Age                 28
Tm                 BOS
G                   61
GS                  61
MP                32.1
FG                 4.1
FGA                9.9
FG%              0.415
3P                 1.9
3PA                5.6
3P%              0.336
2P                 2.2
2PA                4.3
2P%              0.519
eFG%             0.511
FT                 1.4
FTA                1.9
FT%              0.746
ORB                0.8
DRB                2.4
TRB                3.1
AST                6.3
STL                1.5
BLK                0.4
TOV                2.3
PF                 2.8
PTS               11.5
Name: 572, dtype: object)
(590, Rk                 465
Player    Jayson Tatum
Pos                 PF
Age                 24
Tm                 BOS
G                   74
GS                  74
MP                36.9
FG                 9.8
FGA               21.1
FG%              0.466
3P                 3.2
3PA                9.3
3P%               0.35
2P                 6.6
2PA               11.8
2P%              0.558
eFG%             0.543
FT                 7.2
FTA                8.4
FT%              0.854
ORB                1.1
DRB                7.7
TRB                8.8
AST                4.6
STL                1.1
BLK                0.7
TOV                2.9
PF                 2.2
PTS               30.1
Name: 590, dtype: object)
(621, Rk                488
Player    Noah Vonleh
Pos                 C
Age                27
Tm                BOS
G                  23
GS                  1
MP                7.4
FG                0.5
FGA                 1
FG%             0.458
3P                  0
3PA               0.2
3P%              0.25
2P                0.4
2PA               0.9
2P%               0.5
eFG%            0.479
FT                0.1
FTA               0.1
FT%                 1
ORB               0.8
DRB               1.3
TRB               2.1
AST               0.3
STL               0.1
BLK               0.3
TOV               0.5
PF                1.5
PTS               1.1
Name: 621, dtype: object)
(646, Rk                  509
Player    Derrick White
Pos                  SG
Age                  28
Tm                  BOS
G                    82
GS                   70
MP                 28.3
FG                  4.3
FGA                 9.2
FG%               0.462
3P                  1.8
3PA                 4.8
3P%               0.381
2P                  2.5
2PA                 4.5
2P%               0.548
eFG%               0.56
FT                    2
FTA                 2.3
FT%               0.875
ORB                 0.6
DRB                 2.9
TRB                 3.6
AST                 3.9
STL                 0.7
BLK                 0.9
TOV                 1.2
PF                  2.2
PTS                12.4
Name: 646, dtype: object)
(654, Rk                   517
Player    Grant Williams
Pos                   PF
Age                   24
Tm                   BOS
G                     79
GS                    23
MP                  25.9
FG                   2.7
FGA                    6
FG%                0.454
3P                   1.5
3PA                  3.7
3P%                0.395
2P                   1.3
2PA                  2.3
2P%                0.546
eFG%               0.575
FT                   1.2
FTA                  1.5
FT%                 0.77
ORB                  1.1
DRB                  3.5
TRB                  4.6
AST                  1.7
STL                  0.5
BLK                  0.4
TOV                    1
PF                   2.4
PTS                  8.1
Name: 654, dtype: object)
(661, Rk                    524
Player    Robert Williams
Pos                     C
Age                    25
Tm                    BOS
G                      35
GS                     20
MP                   23.5
FG                    3.6
FGA                   4.9
FG%                 0.747
3P                      0
3PA                     0
3P%                     0
2P                    3.6
2PA                   4.8
2P%                 0.751
eFG%                0.747
FT                    0.7
FTA                   1.2
FT%                  0.61
ORB                     3
DRB                   5.4
TRB                   8.3
AST                   1.4
STL                   0.6
BLK                   1.4
TOV                     1
PF                    1.9
PTS                     8
Name: 661, dtype: object)

In [341]:
for index, row in celtics.iterrows():
    print(row['Player'], row['PTS'])

Malcolm Brogdon 14.9
Jaylen Brown 26.6
Justin Champagnie 2.5
JD Davison 1.6
Blake Griffin 4.1
Sam Hauser 6.4
Al Horford 9.8
Justin Jackson 0.9
Mfiondu Kabengele 1.5
Luke Kornet 3.8
Mike Muscala 5.9
Payton Pritchard 5.6
Marcus Smart 11.5
Jayson Tatum 30.1
Noah Vonleh 1.1
Derrick White 12.4
Grant Williams 8.1
Robert Williams 8.0

In [342]:
for row in celtics.itertuples():
    print(row.Player, row.PTS)

Malcolm Brogdon 14.9
Jaylen Brown 26.6
Justin Champagnie 2.5
JD Davison 1.6
Blake Griffin 4.1
Sam Hauser 6.4
Al Horford 9.8
Justin Jackson 0.9
Mfiondu Kabengele 1.5
Luke Kornet 3.8
Mike Muscala 5.9
Payton Pritchard 5.6
Marcus Smart 11.5
Jayson Tatum 30.1
Noah Vonleh 1.1
Derrick White 12.4
Grant Williams 8.1
Robert Williams 8.0

In [343]:
ppg = []

In [344]:
for row in celtics.itertuples():
    ppg.append(row.PTS)

In [345]:
ppg

[14.9,
 26.6,
 2.5,
 1.6,
 4.1,
 6.4,
 9.8,
 0.9,
 1.5,
 3.8,
 5.9,
 5.6,
 11.5,
 30.1,
 1.1,
 12.4,
 8.1,
 8.0]

# Applying Functions to Dataframes

In [347]:
df.sample(5)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
659,522,Mark Williams,C,21,CHO,43,17,19.3,3.7,5.8,...,0.691,2.2,4.9,7.1,0.4,0.7,1.0,0.9,2.2,9.0
319,250,Carlik Jones,PG,25,CHI,7,0,8.0,0.9,2.1,...,0.625,0.1,0.6,0.7,0.9,0.3,0.0,0.3,0.3,2.9
648,511,Joe Wieskamp,SF,23,TOR,9,0,5.6,0.3,1.6,...,0.000,0.0,0.4,0.4,0.3,0.0,0.0,0.1,0.3,1.0
208,163,Josh Giddey,SG,20,OKC,76,76,31.1,7.1,14.7,...,0.731,1.9,5.9,7.9,6.2,0.8,0.4,2.8,1.9,16.6
376,295,Kenneth Lofton Jr.,PF,20,MEM,24,1,7.3,2.0,3.9,...,0.593,0.8,1.3,2.1,0.8,0.2,0.1,0.5,1.2,5.0

In [348]:
# define a function that adds a year to the age of players
def add_year(current_age):
    new_age = current_age + 1
    return new_age

In [350]:
df['Age'].apply(add_year)

0      24
1      30
2      26
3      23
4      23
       ..
674    35
675    25
676    25
677    31
678    26
Name: Age, Length: 679, dtype: int64

In [351]:
# define a function that calculates the points per game for each player

In [352]:
player_stats = {'player_name': ['Tatum', 'Durant', 'Butler', 'Davis', 'Jokic'], 
        'season_id': ['2022-23', '2022-23', '2022-23', '2022-23', '2022-23'], 
        'total_points': [2423, 2390, 495, 539, 1928],
        'games_played': [78, 65, 51, 32, 69]}
df = pd.DataFrame(player_stats)

In [354]:
df

  player_name season_id  total_points  games_played
0       Tatum   2022-23          2423            78
1      Durant   2022-23          2390            65
2      Butler   2022-23           495            51
3       Davis   2022-23           539            32
4       Jokic   2022-23          1928            69

In [355]:
def calc_ppg(row):
    gp = row[3]
    points = row[2]
    return points / gp

In [360]:
df['ppg'] = round(df.apply(calc_ppg, axis=1), 1)
df

  player_name season_id  total_points  games_played   ppg
0       Tatum   2022-23          2423            78  31.1
1      Durant   2022-23          2390            65  36.8
2      Butler   2022-23           495            51   9.7
3       Davis   2022-23           539            32  16.8
4       Jokic   2022-23          1928            69  27.9

In [362]:
df = pd.read_csv('../stats-csv/player-stats-regular-season-22-23.csv', sep=';', encoding='latin1')
df.sample(5)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
308,241,Isaiah Joe,SG,23,OKC,73,10,19.1,3.1,7.0,...,0.820,0.4,2.0,2.4,1.2,0.7,0.1,0.5,1.4,9.5
149,116,Matthew Dellavedova,PG,32,SAC,32,0,6.7,0.5,1.6,...,0.571,0.0,0.4,0.4,1.3,0.2,0.0,0.3,0.6,1.5
560,437,Alperen Þengün,C,20,HOU,75,72,28.9,5.9,10.7,...,0.715,3.2,5.8,9.0,3.9,0.9,0.9,2.6,3.4,14.8
193,148,Simone Fontecchio,SF,27,UTA,52,6,14.7,2.2,6.0,...,0.795,0.6,1.1,1.7,0.8,0.3,0.2,0.8,1.2,6.3
496,387,Aleksej Pokusevski,PF,21,OKC,34,25,20.6,3.2,7.3,...,0.629,1.3,3.4,4.7,1.9,0.6,1.3,1.3,1.7,8.1

In [363]:
# define a function that calculates the total points for each player

In [368]:
def total_points(row):
    total = row['PTS'] * row['G']
    return round(total, 0)

In [369]:
df['Total_Points'] = df.apply(total_points, axis=1)
df.sample(5)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Total_Points
437,348,Markieff Morris,PF,33,TOT,35,2,10.1,1.3,3.3,...,0.4,1.7,2.0,0.9,0.3,0.1,0.5,1.4,3.8,133.0
12,11,Giannis Antetokounmpo,PF,28,MIL,63,63,32.1,11.2,20.3,...,2.2,9.6,11.8,5.7,0.8,0.8,3.9,3.1,31.1,1959.0
518,407,Cam Reddish,SF,23,POR,20,12,27.6,3.9,8.8,...,0.6,2.3,2.9,1.9,1.2,0.3,1.6,2.0,11.0,220.0
334,262,Frank Kaminsky,C,29,ATL,26,0,6.8,1.0,1.7,...,0.1,1.3,1.4,0.8,0.2,0.0,0.3,0.8,2.7,70.0
262,205,Gordon Hayward,SF,32,CHO,50,50,31.5,5.5,11.6,...,0.7,3.6,4.3,4.1,0.8,0.2,2.0,1.4,14.7,735.0

# Arrays

In [371]:
tatum_steals = [2, 1, 0, 0, 3]
tatum_steals

[2, 1, 0, 0, 3]

In [373]:
steals_array = np.array(tatum_steals)
steals_array

array([2, 1, 0, 0, 3])

In [374]:
steals_array.mean()

1.2

In [392]:
steals_array = steals_array + 2
steals_array

array([38, 37, 36, 36, 39])

In [394]:
steals_array.shape

(5,)